### ISSUE TITLE
Rename Cheat to prevent Conflict

### ISSUE THREAD

**Issue by whiteadam** [alexanderepstein/Bash-Snippets#109]
**Issue Label:**
* [x] Enhancement

**Description:**
I was wondering if `cheat` could be renamed so that it doesn't conflict with this version of cheat: https://github.com/chrisallenlane/cheat

I actually use the above version quite often. To check it out, `brew install cheat` on Mac.

### If its a bug make sure to include this section.
**OS and OS version:**
* [X] Mac

* [X] Linux 64 Bit

OS Version:
10.12.6

**Comment by alexanderepstein** [comment]
I will look into doing this, it is hard for me to change the name of the tool only because of the way my main install,update and uninstall pipeline works. I will try to find an easier way than the one I am thinking of now and maybe it won't be so hard. Thanks for letting me know about the name conflict! (Any new name suggestions welcome)

**Comment by alexanderepstein** [comment]
Can you run ```which cheat``` when bash-snippets is not installed? I want to see where your version of cheat stores their file, might help me in this process.

**Comment by whiteadam** [comment]
Here you go:
```
[~/Code] ls -ln $(which cheat)
lrwxr-xr-x  1 501  0  31 Jul 28 10:50 /usr/local/bin/cheat -> ../Cellar/cheat/2.2.0/bin/cheat
[~/Code]
```

As for new names... cheats, cheatr, cheatcode? I kindof like cheatcode :)

**Comment by alexanderepstein** [comment]
Awesome thanks, I like those names we will see which one it becomes :smile_cat:

**Comment by alexanderepstein** [comment]
I am thinking a possible solution instead of renaming cheat would be to allow for parameters to be passed to the install that allows you to install certain tools or choose not to install certain tools and the default would be a complete install. 

So something like ```brew install bash-snippets --without cheat``` or ```brew install bash -snippets --only cloudup```. Do you think that would solve the issue here? It seems like if you use that other project you wouldn't use my version of cheat correct?

**Comment by alexanderepstein** [comment]
With the new brew formula you'll be required to ```brew unlink```, but not uninstall, the conflict before installing, like this:
```bash
iMac-TMP:~ joe$ brew install cheat
==> Downloading https://homebrew.bintray.com/bottles/cheat-2.2.0.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring cheat-2.2.0.el_capitan.bottle.tar.gz
==> Using the sandbox
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/cheat/2.2.0: 839 files, 8MB
iMac-TMP:~ joe$ brew install bash-snippets
Error: Cannot install bash-snippets because conflicting formulae are installed.
  cheat: because Both install a `cheat` executable

Please `brew unlink cheat` before continuing.

Unlinking removes a formula's symlinks from /usr/local. You can
link the formula again after the install finishes. You can --force this
install, but the build may fail or cause obscure side-effects in the
resulting software.
iMac-TMP:~ joe$ brew unlink cheat
Unlinking /usr/local/Cellar/cheat/2.2.0... 3 symlinks removed
iMac-TMP:~ joe$ brew install bash-snippets
==> Using the sandbox
==> Downloading https://github.com/alexanderepstein/Bash-Snippets/archive/v1.16.0.tar.gz
==> Downloading from https://codeload.github.com/alexanderepstein/Bash-Snippets/tar.gz/v1.16.0
######################################################################## 100.0%
==> ./install.sh --prefix=/usr/local/Cellar/bash-snippets/1.16.0 all
🍺  /usr/local/Cellar/bash-snippets/1.16.0: 22 files, 151.3KB, built in 6 seconds
```
Note you can still use the other cheat at that point:
```bash
iMac-TMP:~ joe$ which cheat
/usr/local/bin/cheat
iMac-TMP:~ joe$ mdutil -t `which cheat`
/usr/local/Cellar/bash-snippets/1.16.0/bin/cheat
iMac-TMP:~ joe$ export PATH=/usr/local/opt/cheat/bin:$PATH
iMac-TMP:~ joe$ which cheat
/usr/local/opt/cheat/bin/cheat
iMac-TMP:~ joe$ mdutil -t `which cheat`
/usr/local/Cellar/cheat/2.2.0/libexec/bin/cheat
iMac-TMP:~ joe$ 
```

**Comment by whiteadam** [comment]
Hah! Nice, thanks Alex... Now I can cheat my way through life :)
