### ISSUE TITLE
`checkInternet()` is broken in some countries.

### ISSUE THREAD

**Issue by hxgdzyuyi** [alexanderepstein/Bash-Snippets#112]
**Issue Label:**
* [x] Bug
* [ ] New feature
* [ ] Enhancement
* [ ] New component

**Description:**

Bash-Snippets use `httpGet google.com` in `checkInternet()`.

People have been unable to access certain Google products and services at some point in more than 30 countries.

See more: https://www.google.com/transparencyreport/traffic/#expand=CG

**Comment by alexanderepstein** [comment]
Will use a webservice that works worldwide, possibly thinking github itself?

**Comment by alexanderepstein** [comment]
Seems like github was banned but is has been removed from the great red firewall. Will make this switch for the next release.

**Comment by alexanderepstein** [comment]
Should be fixed in a5fdff610c2e1bcd067ab498bf83e8635da67745

**Comment by alexanderepstein** [comment]
Fixed in [v1.17.3](https://github.com/alexanderepstein/Bash-Snippets/releases/tag/v1.17.3)
