### ISSUE TITLE
bc not native to all OS's

### ISSUE THREAD

**Issue by N3V0N** [alexanderepstein/Bash-Snippets#113]
* [x] Bug

**Description:**

What is the base currency: BTC
What currency to exchange to: USD
What is the amount being exchanged: 2
/usr/local/bin/cryptocurrency: line 169: bc: command not found
=========================
| BTC to USD
| Rate: 2698.42
| BTC: 2
| USD: 
=========================

### If its a bug make sure to include this section.
**OS and OS version:**
* [x] Linux 64 Bit
Parrot Security OS

**Comment by alexanderepstein** [comment]
Wow, I don't think I have encountered an OS that does not have bc natively installed. Would you be able to run the following lines in your terminal. I want to see if you can perform math in the bash only way. 
```bash
test=$(( 1+ 1 ))
echo $test
```
If this prints out ```2``` then we are good to go and I can fix the issue. If it doesn't produce a ```2``` the only thing I could think of would be to install ```bc``` on your system.

**Comment by alexanderepstein** [comment]
The ```todo``` tool should have similar problems, and so should any other tool that uses bc

**Comment by alexanderepstein** [comment]
Ah i had to use bc bash cannot do any math outside of integers. So converting between currencies would only be an approximation (could only do the math if I truncate the decimals).

**Comment by alexanderepstein** [comment]
This commit d8980a0a9c906eb2be3d392eaafb4bf97d40b74f should fix the issue for the most part. It will truncate the decimal off the exchange rate and perform the conversion then.

**Comment by alexanderepstein** [comment]
running ```sudo apt-get install bc``` would be better however as the other fix will result in an approximation rather then a definite answer.

**Comment by N3V0N** [comment]
I think that 'bc' wasn't preinstalled properly because the result of `test=$(echo 1 + 1 | bc ) && echo $test || echo Error` was 2 but the script did not work, so I installed it by `sudo apt install bc` and the scripts work

**Comment by alexanderepstein** [comment]
Huh interesting, well at least they work for you now. I have accounted for bc not existing on the system, but I cannot account for if it doesn't work properly. Thanks for making me aware of this issue :)

**Comment by N3V0N** [comment]
I am Running Parrot Security OS 64 bit jolly rogers

**Comment by alexanderepstein** [comment]
Fixed in [v1.17.3](https://github.com/alexanderepstein/Bash-Snippets/releases/tag/v1.17.3)
