### ISSUE TITLE
Add support for fetching lyrics of song from command line.

### ISSUE THREAD

**Issue by tushar-saxena** [alexanderepstein/Bash-Snippets#118]
**Issue Label:**
* [ ] Bug
* [ ] New feature
* [ ] Enhancement
* [x] New component

**Description:**

**Comment by alexanderepstein** [comment]
Haven't really found a good free API for this. Will leave this issue here for a little for anyone who wants to try creating this. Follow the guide in [CONTRIBUTING](https://github.com/alexanderepstein/Bash-Snippets/blob/master/CONTRIBUTING.md) for instructions on creating a new component.

**Comment by m1guelpf** [comment]
Maybe you can do this with Musixmatch API...

**Comment by alexanderepstein** [comment]
Musixmatch API only provides 30% of the song lyrics with their free plan https://developer.musixmatch.com/plans

**Comment by glundgren93** [comment]
There are a couple of other options:

- https://api.vagalume.com.br/docs/letras/
- http://docs.lyricsovh.apiary.io
- https://docs.genius.com/

**Comment by alexanderepstein** [comment]
Using @glundgren93 's second option i have created the initial version of the lyrics tool in this commit 89a4d1f32eb171af0607008fbebbe927ad760b32

**Comment by alexanderepstein** [comment]
Added in [Version 1.19.0](https://github.com/alexanderepstein/Bash-Snippets/releases/tag/v1.19.00
