### ISSUE TITLE
url Expander

### ISSUE THREAD

**Issue by Logic-gate** [alexanderepstein/Bash-Snippets#12]
**Issue Label:**
* [ ] bug
* [ ] feature
* [x] enhancement

**Description of bug or feature enhancement:**
Add a url expander. I currently have a working web service. Example http://x.datasig.io/short?url=http://tinyurl.com/jhkj/

**Comment by alexanderepstein** [comment]
@Logic-gate added in ccb751ec01b25ec020b4983f312cbe4eda190c66 will come out with next release
