### ISSUE TITLE
Domain change | short

### ISSUE THREAD

**Issue by Logic-gate** [alexanderepstein/Bash-Snippets#122]
x.datasig.io is now http://ki.tc
Same parameters and output, a simple domain name change

`
   http://ki.tc/short?url=http://tinyurl.com/jhkjh78
`

``` 
  {
  "/short": {
    "destination": "https://www.tripleclicks.com/14296529/detail?item=498072", 
    "short_url": "http://tinyurl.com/jhkjh78"
  }
}
```

https://github.com/alexanderepstein/Bash-Snippets/blob/51caa49c488d03b2f87202a9bc83f408a4ff67c6/short/short#L137

**Comment by alexanderepstein** [comment]
Thanks for letting me know this has been accounted for in 566cf8c810dd9c1a971ab298cd2e8cdcc3b5bbd2 :tada: !
