### ISSUE TITLE
Lyrics Tool Always Failing

### ISSUE THREAD

**Issue by alexanderepstein** [alexanderepstein/Bash-Snippets#128]
**Issue Label:**
* [x] Bug
* [ ] New feature
* [ ] Enhancement
* [ ] New component

**Description:**
https://lyrics.ovh/ doesn't seem to be a website. The tool for now will go in a deprecated folder and will sit there until someone comes along and finds a new free lyrics api with unlimited requests.

### If its a bug make sure to include this section.
**OS and OS version:**
All

**Comment by alexanderepstein** [comment]
Fixed by removing the lyrics tool from the main installer and checking to see if I can remove it during an uninstall. Should probably check to uninstall this tool during the install but, might run into issues for people who installed a previous version through homebrew.

Lyrics was removed in [Version 1.19.2](https://github.com/alexanderepstein/Bash-Snippets/releases/tag/v1.19.2)

**Comment by Diskutant** [comment]
Website and api works fine for me?

**Comment by alexanderepstein** [comment]
Yeah seems to work now, I had tested this before and it was not working, went over to the website and it seemed to be gone, looks like its back, will try to bring back this tool in the next release
