### ISSUE TITLE
Without $LANG var being set weather was not shown

### ISSUE THREAD

**Issue by farhansalam** [alexanderepstein/Bash-Snippets#13]
**Issue Label:**
* [ ✔ ] enhancement

**Description of bug or feature enhancement:**

Without $LANG var being set weather was not populated

**OS and OS version:**
* [✔ ] Mac

OS Version:
10.12.5 (16F73)

**Comment by farhansalam** [comment]
Fixed here https://github.com/alexanderepstein/Bash-Snippets/pull/14

**Comment by alexanderepstein** [comment]
Really? This variable should be a builtin so every system should have a value there, but I guess it cannot hurt to have a default value

**Comment by alexanderepstein** [comment]
Merged 4f44a45ba19932da064988bc4189ac9444f29b9b

**Comment by farhansalam** [comment]
Yes, unfortunately it was empty I am using latest zsh version `zsh 5.2 (x86_64-apple-darwin16.0.0)`. But anyways, thanks for the merge! 👍
