### ISSUE TITLE
Stock URL is outdated

### ISSUE THREAD

**Issue by CMiksche** [alexanderepstein/Bash-Snippets#131]
**Issue Label:**
* [x] Bug
* [ ] New feature
* [ ] Enhancement
* [ ] New component

**Description:**
Your stock URL is outdated. GLOBAL_QUOTE isn't available anymore from alphavantage.co.

Example:

URL: https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=AAPL&apikey=KPCCCRJVMOGN9L6T

Result:

    {
        "Error Message": "The API function encountered an internal or external error - we apologize for the 
    inconvenience. "
    }

See the API Documentation for a alternative: https://www.alphavantage.co/documentation/

**OS and OS version:**
* [x] Mac
* [x] Linux 32 Bit
* [x] Linux 64 Bit
* [x] Windows 32 Bit
* [x] Windows 64 Bit

OS Version: All

**Comment by alexanderepstein** [comment]
Thanks for letting me know :+1: , I am super busy with schoolwork currently and might not be able to get to this for 2-3 weeks. If you or anyone else wanted to submit a pull request where the output matches how it previously worked I would be more than glad to test and merge. Just don't have the time right now :clock1130:

**Comment by navanchauhan** [comment]
@alexanderepstein Why don't you add someone else as contributor, so they can help lessen the burden

**Comment by alexanderepstein** [comment]
@navanchauhan I wouldn't mind doing that I just haven't had anyone who has made a few contributions who offers to become a contributor

**Comment by alexanderepstein** [comment]
It looks like with the new api offered by them i cannot grab all the same information using just one web request, and even then the way I would have to parse it amongst calculations I would have to do will make this a lot harder than it previously was. With that I am looking for a new api to get this info from and definitely will take suggestions.

**Comment by CMiksche** [comment]
@alexanderepstein 
> With that I am looking for a new api to get this info from and definitely will take suggestions.

Have you considered the Yahoo Finance API? It allows to grab a lot of information even without api key.

Sample request, returning a csv file:
`http://finance.yahoo.com/d/quotes.csv?s=AAPL&f=sabd`

The problem with this api is, yahoo has also changed its api ... 
(Sample: https://stackoverflow.com/questions/44057580/yahoo-finance-api-changes-2017)

**Comment by alexanderepstein** [comment]
Sorry this is taking longer than expected, its hard to find an api that was as consistent as alphavantage. I might just end up using alphavantage again but get rid of some of the metrics that was present previously, does that sound good? Otherwise im on the hunt for an api that is a little more documented than the yahoo api

**Comment by navanchauhan** [comment]
https://iextrading.com/developer/ and https://www.barchart.com/ondemand/free-market-data-api might be good alternatives

**Comment by navanchauhan** [comment]
I really think IEX might be good

**Comment by navanchauhan** [comment]
Just wait for 100 minutes i.e 1hr 40mins and I would have an alternative stocks script ready

**Comment by navanchauhan** [comment]
Pull Request #139 fixes this issue

**Comment by navanchauhan** [comment]
So I'm closing this issue, if the pull request does not get accepted this issue will be opened again

**Comment by navanchauhan** [comment]
@alexanderepstein or @CMiksche You should close this now

**Comment by alexanderepstein** [comment]
Fixed with #139
