### ISSUE TITLE
Issue with cloudup not resolving host

### ISSUE THREAD

**Issue by jbhouse** [alexanderepstein/Bash-Snippets#133]
**Issue Label:**
* [x] Bug
* [ ] New feature
* [ ] Enhancement
* [ ] New component

**Description:**

When trying to use cloudup to clone a github repo to bit bucket i get the bellow error. I couldn't seem to find any similar errors/fixes through googling. other possibly relevant information- doing this through a windows 10 ubuntu terminal

Uploading hangman to bitbucket                                                                                                                                                         fatal: unable to access 'https://jbhacks:@bitbucket.org/jbhacks/hangmansun_nov__5_19_18_45_std_2017.git/': Could not resolve host: jbhacks                                    Error: couldnt backup hangman to bitbucket 

### If its a bug make sure to include this section.
**OS and OS version:**
* [ ] Mac
* [ ] Linux 32 Bit
* [x] Linux 64 Bit
* [ ] Windows 32 Bit
* [x] Windows 64 Bit

OS Version:

**Comment by alexanderepstein** [comment]
Can you check to see if the repository has been created on the bitbucket account? My first guess is that the repo itself wasn't actually created. 

Can you also tell me what the exact command you ran was it seems like it was ```cloudup -t hangman``` but just want to be sure.  

As a last measure can you run the identical command but prefix it with bash -x and post the output here? This will let me see exactly what happened. Ex. ```bash -x cloudup -t hangman```

 I also want to make sure that it is your bitbucket account as the name nor the username match what you have here on github. I assume it is your account but if its not the authentication will not work as the bitbucket password and username will not correspond.

**Note: cloudup uses http authentication which means your bitbucket password will be present in the output of what I'm asking for, please look to remove the password where you see it within the output, you accidently posted it in this issue but I removed it for you***

**Comment by jbhouse** [comment]
previously i believe i just ran cloudup and then was prompted for the rest o the information
this time i tried to run it with cloudup -t hangman like you asked and this happened. 
rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/hooks/pre-receive.sample': Permission denied                                                                                                               rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/hooks/prepare-commit-msg.sample': Permission denied                                                                                                        rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/hooks/update.sample': Permission denied                                                                                                                    rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/index': Permission denied                                                                                                                                  rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/info/exclude': Permission denied                                                                                                                           rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/logs/HEAD': Permission denied                                                                                                                              rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/logs/refs/heads/master': Permission denied                                                                                                                 rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/logs/refs/remotes/origin/HEAD': Permission denied                                                                                                          rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/objects/0c/f9a7ed8903d99147cd70a5ebd9f3a2d7b528a5': Permission denied                                                                                      rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/objects/2c/8956487324ea2ec6db9d658ff426dc25354866': Permission denied                                                                                      rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/objects/30/fb03a401973b1c5866343b073ded467153f00d': Permission denied                                                                                      rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/objects/39/6dcb093633f2e7eb2c6f7f90b860ea2cc87c0d': Permission denied                                                                                      rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/objects/4b/cfa39e836aaf93cb30ffb0f975733405982e26': Permission denied                                                                                      rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/objects/4d/151ba7399aed1560a2477c237914d27e302d6c': Permission denied                                                                                      rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/objects/4e/249b6e58da5e3d38aff846babe16e4bfbaf702': Permission denied                                                                                      rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/objects/51/04bbda697fede1e0f19165f9573f0b89968144': Permission denied                                                                                      rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/objects/53/4809f59186181857ed924886fe766527225cfe': Permission denied                                                                                      rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/objects/6b/468b62a9884e67ca19b673f8e14e1931d65036': Permission denied                                                                                      rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/objects/72/857efb00a9798984caf38e403043f2d945bba9': Permission denied                                                                                      rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/objects/7b/3e7db2e7b41f327e35c2a32bd67f2233881132': Permission denied                                                                                      rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/objects/8b/202dfc60ac4bea7491982b6e4b208afb0b251d': Permission denied                                                                                      rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/objects/8d/c09ab5067b19f4a1f5fb0a5d69227b07b042b6': Permission denied                                                                                      rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/objects/92/e7eed6aa78124047b818ef240a8911d6bdd341': Permission denied                                                                                      rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/objects/96/73ebc48457a604a295929b491e8928cc54389a': Permission denied                                                                                      rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/objects/a0/6cd25982fde760181a049789eb11e413363ed8': Permission denied                                                                                      rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/objects/b5/96484c6219e53e71025600c936f0990322c9ac': Permission denied                                                                                      rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/objects/bb/35fa0a87b032ee9d0b128004c1edbd464f07bf': Permission denied                                                                                      rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/objects/c1/41d78aa57969bad63fc0d2e385aa716364064f': Permission denied                                                                                      rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/objects/c2/0cacfed2acc6e739bc82c418679a5b1bc42542': Permission denied                                                                                      rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/objects/ca/8db99520393ac938afb6f64deed79822a22fbb': Permission denied                                                                                      rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/objects/d8/10f7d1ba627233c85ac3aa88332a6ca0ff6da3': Permission denied                                                                                      rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/objects/dd/3a7918c44f64bd49559e217fe1e771bd3afc12': Permission denied                                                                                      rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/objects/e4/61bea9f1544fa66467ba697b03628a75d617df': Permission denied                                                                                      rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/objects/e6/e5cc1d587cd1d025b5d057145bf6c8ec9ea07f': Permission denied                                                                                      rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/objects/e7/d73b6cbc94219731e29f75f91191eba7258254': Permission denied                                                                                      rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/objects/fd/0b0f941a1320c8cfc5f947e6b61ae1dd6ca90e': Permission denied                                                                                      rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/objects/info': Permission denied                                                                                                                           rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/objects/pack': Permission denied                                                                                                                           rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/packed-refs': Permission denied                                                                                                                            rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/refs/heads/master': Permission denied                                                                                                                      rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/refs/remotes/origin/HEAD': Permission denied                                                                                                               rm: cannot remove '/home/jbhouse/temp/github/hangman/.git/refs/tags': Permission denied                                                                                                                              rm: cannot remove '/home/jbhouse/temp/github/hangman/.gitignore': Permission denied                                                                                                                                  rm: cannot remove '/home/jbhouse/temp/github/hangman/hangman/.classpath': Permission denied                                                                                                                          rm: cannot remove '/home/jbhouse/temp/github/hangman/hangman/.project': Permission denied                                                                                                                            rm: cannot remove '/home/jbhouse/temp/github/hangman/hangman/.settings/org.eclipse.jdt.core.prefs': Permission denied                                                                                                rm: cannot remove '/home/jbhouse/temp/github/hangman/hangman/src/hangman/Game.java': Permission denied                                                                                                               /usr/local/bin/cloudup: illegal option -- t                                                                                                                                                                          Invalid option: - 

running bash -x cloudup -t hangman resulted in a nearly identical error message, but with the following appended to it
+ getConfiguredClient                                                                                                                                                                                                + command -v curl                                                                                                                                                                                                    + configuredClient=curl                                                                                                                                                                                              + checkInternet                                                                                                                                                                                                      + echo -e 'GET http://google.com HTTP/1.0\n\n'                                                                                                                                                                       + nc google.com 80                                                                                                                                                                                                   + '[' 0 -eq 0 ']'                                                                                                                                                                                                    + return 0                                                                                                                                                                                                           + getopts pauvh opt                                                                                                                                                                                                  cloudup: illegal option -- t                                                                                                                                                                                         + case $opt in                                                                                                                                                                                                       + echo 'Invalid option: -'                                                                                                                                                                                           Invalid option: -                                                                                                                                                                                                    + exit 1     

hopefully this helps. and lastly, thank you fir removing my bitbucket password

**Comment by alexanderepstein** [comment]
Well there is one issue i see off the bat, you are using an old version of Bash-snippets and should update it, many bug fixes have been made and quite possibly one of them solving your issue, try running ```cloudup -u``` and follow the onscreen prompts to update bash-snippets  we can work from there.

**Comment by alexanderepstein** [comment]
I'm going to close this issue as I cannot resolve it without your input. I hope that it started to work after you updated.
