### ISSUE TITLE
Error: no active internet connection

### ISSUE THREAD

**Issue by TuXbOy06** [alexanderepstein/Bash-Snippets#148]
**Issue Label:**
* [x ] Bug
* [ ] New feature
* [ ] Enhancement
* [ ] New component

**Description:**
When doing a weather France for example I am getting an error 
"Error: no active internet connection"
I can confim that I have internet and local firewalls

### If its a bug make sure to include this section.
**OS and OS version:**
* [ ] Mac
* [ ] Linux 32 Bit
* [x ] Linux 64 Bit
* [ ] Windows 32 Bit
* [ ] Windows 64 Bit

OS Version:
Archlinux

**Comment by alexanderepstein** [comment]
Can you run ```bash -x weather France``` and put the output here? I assume if this tool doesn't work then none of the other tools really will work since they all utilize the checkInternet function which basically just curl/wget/httpie/fetchs github.com if there is an error it assumes you don't have Internet connection.
