### ISSUE TITLE
add support for rate.sx

### ISSUE THREAD

**Issue by chubin** [alexanderepstein/Bash-Snippets#152]
**Issue Label:**
* [X] Enhancement

**Description:**

rate.sx — it's a new console service for getting cryptocurrencies exchange rates.
It delivers various information about the most popular (by market capitalization)
cryptocurrencies: exchange rate, change in 1h and 24h, market capitalization, volume
etc. It is completely clientless, and needs no special dependencies, can be used with curl/httpie/etc like wttr.in or cheat.sh.

It would be great to integrate it in Bash-Snippets.

**Comment by alexanderepstein** [comment]
I will definitely add this as a flag to the cryptocurrency tool I love the way the output looks any chance I could add a flag to the end of the url that would specify if I want it in EUR or usd? I if I could it would probably become the default for the cryptocurrency tool and I would make the current functionality only accessible with a flag

**Comment by chubin** [comment]
@alexanderepstein Hi Alex! Yes, there is the chance: just use 
```
curl eur.rate.sx
curl chf.rate.sx
curl gbp.rate.sx
```
(or whatever; 10 currencies are supported at the moment).

**Comment by alexanderepstein** [comment]
Awesome! I am definitely going to have this take over for the cryptocurrency tool and reserve the current functionality for a flag. It may take me 2-3 weeks as I am busy with finals and probably won't want to do work for a few days when I get back home :relaxed: :tada:

**Comment by alexanderepstein** [comment]
Can you let me know what 10 currencies are supported atm?

**Comment by chubin** [comment]
Cool!

They are listed here: http://rate.sx/:help

It is likely that the list will grow with time, so you should better check it before releasing the tools (or even check automatically with your tool).

And take a look at another new feature (it is not yet released, but it is cool):

Try: curl http://eur.rate.sx/1usd  or http://rate.sx/1btc+1bch+1btg  or http://cad.rate.sx/0.1btc-2.555eth  (crypto)currency calculator. You can do +,- and convert between any (crypto)currencies

More on it here: https://twitter.com/igor_chubin/status/938161710019633152
(Do you have twitter by the way?)

**Comment by chubin** [comment]
@alexanderepstein yes (balance) and yes (it's a good idea to use Twitter solely to promote/support/discuss your tools; (Imho) it's a funny and strange idea to tweet about your personal life/but it is perfectly ok and even really convenient and efficient to use it as a support channel for your tools).

The idea with the balance is great. We've discussed it already in one of the issues of rate.sx; it will be implemented. So it will be possible to see how much you have on some account; you can count on it.

**Comment by navanchauhan** [comment]
I’m free right now so I can look into implementing it in the script if that’s ok ?

**Comment by alexanderepstein** [comment]
@navanchauhan yeah you can definitely look to start implementing parts of this, it will be a lot to change, I want the old functionality of cryptocurrency tool to still exist but it will with some flag like -o or -d to use the old functionality. Otherwise use rates.sx and also set the code up for being able to call rates.sx for different fiat currencies something like ```cryptocurrency -f eur``` will call eur.rates.sx It would also make sense to have a -a flag that doesnt do anything at the moment but the rest of the code can handle if it exists (this is where the address of a wallet can be supplied)

**Comment by alexanderepstein** [comment]
@chubin Yeah i think I will end up making one when I do Ill give you the handle :smile: 

I also like the idea with balance, I took a shot at something similar with my cryptowatch tool but you did a way better job lol :+1:

**Comment by alexanderepstein** [comment]
First version in this commit ac76f298db3d6632f316aed0fee30526cd014da7

**Comment by elsesiy** [comment]
@alexanderepstein @chubin I'm happy to support as well so we can make it the best CLI tool possible for monitoring crypto currencies 🥇

**Comment by chubin** [comment]
I'm working on several new cool features right now. I bet you will like them.

Apropos monitoring, you could add the "follow" mode to the tool,
so it will notify you if the price drops below something or soars above something.

Just a wrapper around this:
```
watch -gn60 'curl -s eur.rate.sx/1btc-13500eur | grep ^-' > /dev/null ; echo 'To the MOON!' | mail some@email.com
```

Something like 
```
echo cryptocurrency -F 1btc-13500eur some@email.com | at now
```
or just 
```
cryptocurrency -F 1btc-13500eur some@email.com
```
but in the latter case you have to send it to background on your own.

**Comment by elsesiy** [comment]
@alexanderepstein In the current implementation you broke the old functionality. It's not possible to provide the specified `-o` argument...

**Comment by chubin** [comment]
Can we reopen it please?

**Comment by elsesiy** [comment]
Yes I'm with @chubin here. Also the old functionality is still broken so there's no way to query for a certain amount atm.

@alexanderepstein Shall I fix the issue in the current implementation and keep going with Igor or when do you intend to do it?

**Comment by alexanderepstein** [comment]
I did fix the current implementation issue just havent released an update in a while feel free to work with igor on this issue but I have been extremely busy lately so its hard to work on this project

**Comment by elsesiy** [comment]
Okay, let's try to get this going again :) 
@chubin Can you reach out to me via Twitter or something like that? Thanks!

**Comment by elsesiy** [comment]
@chubin What's the status on this?

**Comment by chubin** [comment]
I hope to release a major update for rate.sx soon, and we can continue with this issue then

**Comment by chubin** [comment]
@elsesiy @alexanderepstein  @navanchauhan 
I've released the major update of rate.sx I mentioned above.
Now it's possible not simply do the currency conversion, but also check/visualize conversion rate change/dynamics.

Try:
```
curl rate.sx/eth
curl rate.sx/btc@1w
curl rate.sx/btc/eth
```

**Comment by elsesiy** [comment]
@chubin Is it also possible to retrieve a quota for any given account balance? Let's say user A has 60 BTC and wants to know how much it's worth right now..
