### ISSUE TITLE
README Enhancements

### ISSUE THREAD

**Issue by shaishavgandhi05** [alexanderepstein/Bash-Snippets#157]
**Issue Label:**

* [x]  Enhancement

**Description:**

It would be really helpful if the README file had a one line command with every section. Right now, the images are great for seeing the output, but in some cases, the font becomes really small and is hard to see. Including the command before the image will help with readability. 

I wouldn't mind working on this if there are no objections

**Comment by alexanderepstein** [comment]
Feel free to work on this! If you want you can also run '''man bash-snippets''' for a whole section on what each tool does and how to use them
