### ISSUE TITLE
Youtube View

### ISSUE THREAD

**Issue by Mario253** [alexanderepstein/Bash-Snippets#162]
**Issue Label:**
* [x] Bug
* [ ] New feature
* [ ] Enhancement
* [ ] New component

**Description:**
In the ytview command, I searched for a video, then selected the fourth video that showed up. However, it played the first.

### If its a bug make sure to include this section.
**OS and OS version:**
* [ ] Mac
* [ ] Linux 32 Bit
* [x] Linux 64 Bit
* [ ] Windows 32 Bit
* [ ] Windows 64 Bit

OS Version: 18.04

**Comment by alexanderepstein** [comment]
Did this fix itself? There was a problem with an earlier version that had this behavior the newest version shouldn't

**Comment by Mario253** [comment]
That's probably it. I updated the ytview a little after I posted this, and that's about the time it was fixed.
