### ISSUE TITLE
Meme generator is not working

### ISSUE THREAD

**Issue by prmsrswt** [alexanderepstein/Bash-Snippets#163]
**Issue Label:**
* [x] Bug
* [ ] New feature
* [ ] Enhancement
* [ ] New component

**Description:**
The meme generator does not work due to two bugs I have identified.
1. The website returns a PNG image while the script save it as JPEG, so a user cannot view image until he/she rename it.
2. If we use spaces in text for first or second line it returns an HTML page instead of an PNG image, correct method is using underscore instead of space.

### If its a bug make sure to include this section.
**OS and OS version:**
* [ ] Mac
* [ ] Linux 32 Bit
* [x] Linux 64 Bit
* [ ] Windows 32 Bit
* [ ] Windows 64 Bit

OS Version: Arch Linux

**Comment by navanchauhan** [comment]
Though #168 fixes this, according to the URL the image should actually  be jpg 😅

**Comment by alexanderepstein** [comment]
Closed #169
