### ISSUE TITLE
meme generator does not work with capital letters

### ISSUE THREAD

**Issue by prmsrswt** [alexanderepstein/Bash-Snippets#165]
**Issue Label:**
* [x] Bug
* [ ] New feature
* [ ] Enhancement
* [ ] New component

**Description:**
If we use capital letters in text, we get a html document containing a redirection notice instead of png image. We can turn all capital letters into small letters before calling api to fix this issue.

### If its a bug make sure to include this section.
**OS and OS version:**
* [ ] Mac
* [ ] Linux 32 Bit
* [x] Linux 64 Bit
* [ ] Windows 32 Bit
* [ ] Windows 64 Bit

OS Version: Arch Linux

**Comment by navanchauhan** [comment]
#168 Fixes This

**Comment by alexanderepstein** [comment]
Closed #169
