### ISSUE TITLE
Arch Linux install via package manager failure

### ISSUE THREAD

**Issue by TheLinuxNinja** [alexanderepstein/Bash-Snippets#170]
**Issue Label:**
* [X] Bug
* [ ] New feature
* [ ] Enhancement
* [ ] New component

**Description:**
Using bauerbill to install bash-snippets from Arch Linux AUR
https://aur.archlinux.org/packages/bash-snippets/

$ bb-wrapper --aur -S bash-snippets
created build/download.sh
created build/build.sh
~/build ~
[2018-07-30 02:48:46] INFO: searching AUR
Already up to date.
[2018-07-30 02:48:47] INFO: found bash-snippets at https://aur.archlinux.org/bash-snippets.git
~/build/bash-snippets ~/build
bash-snippets : 4262
~/build
==> Making package: Bash-Snippets 1.18.0-2 (Mon 30 Jul 2018 02:48:48 AM EDT)
==> WARNING: Skipping dependency checks.
==> Retrieving sources...
  -> Found v1.18.0.tar.gz
==> Validating source files with sha256sums...
    v1.18.0.tar.gz ... Passed
~/build/bash-snippets ~/build
==> Making package: Bash-Snippets 1.18.0-2 (Mon Jul 30 02:48:49 EDT 2018)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found v1.18.0.tar.gz
==> Validating source files with sha256sums...
    v1.18.0.tar.gz ... Passed
==> Extracting sources...
  -> Extracting v1.18.0.tar.gz with bsdtar
==> Removing existing $pkgdir/ directory...
==> Entering fakeroot environment...
==> Starting package()...
Installing cheat: Failure
Error copying file, try running install script as sudo
==> ERROR: A failure occurred in package().
    Aborting...

### If its a bug make sure to include this section.
**OS and OS version:**
* [ ] Mac
* [ ] Linux 32 Bit
* [X] Linux 64 Bit
* [ ] Windows 32 Bit
* [ ] Windows 64 Bit

OS Version:
Arch Linux

It appears the AUR has been abandoned. Not sure what, if anything, you can do about it.

**Comment by navanchauhan** [comment]
Try running with ‘sudo’

**Comment by TheLinuxNinja** [comment]
bb-wrapper is run as the normal user, and it calls bauerbill with sudo.

however, running the AUR download.sh build.sh clean.sh scripts must be done as a normal user, not as root.

**Comment by navanchauhan** [comment]
@alexanderepstein Did some researching and found out all of this:

- You shouldn't install Arch Linux packages to usr/local 
- If you need sudo privileges, you should run that particular command with sudo in the script

I think we'll need to create a separate install file for Arch Linux systems

**Comment by navanchauhan** [comment]
#171 + changing PKGBUILD from `install.sh` to `install-arch.sh` will fix this 👍
