### ISSUE TITLE
Concurrency seems bad in Centos7.3

### ISSUE THREAD

**Issue by liuliqiang** [alexanderepstein/Bash-Snippets#172]
**Issue Label:**
* [x] Bug

**Description:**
I try this command: `currency CNY HKD 10 ` and get the output which not show as sample:

```
➜  ~ currency CNY HKD 10   

=========================
| CNY to HKD
| Rate: 1.1474015352
1.0
| CNY: 10
| HKD: 1.1474015352
10.0
=========================
```

### If its a bug make sure to include this section.
**OS and OS version:**
* [x] Linux 64 Bit

OS Version:

```
➜  ~ hostnamectl
   Static hostname: china
... ...
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-862.11.6.el7.x86_64
      Architecture: x86-64
```

**Comment by alexanderepstein** [comment]
Think this has been fixed in b270518de8c96ed1e67fafd7701ae08aa932ec1e, you will have to install from master to use the patch
