### ISSUE TITLE
Uninstall todo

### ISSUE THREAD

**Issue by nanoak** [alexanderepstein/Bash-Snippets#174]
**Issue Label:**
* [ ] Bug
* [ ] New feature
* [ ] Enhancement
* [ ] New component

**Description:**
I'm having a bad time trying to uninstall todo. How can I do thtat in Arch Linux?

### If its a bug make sure to include this section.
**OS and OS version:**
* [ ] Mac
* [ ] Linux 32 Bit
* [x ] Linux 64 Bit
* [ ] Windows 32 Bit
* [ ] Windows 64 Bit

OS Version:
Arch Linux

**Comment by alexanderepstein** [comment]
Did you use the arch script or just the generic install script?
