### ISSUE TITLE
currency not properly displaying output

### ISSUE THREAD

**Issue by SDiamante13** [alexanderepstein/Bash-Snippets#177]
**Issue Label:**
* [ x] Bug
* [ ] New feature
* [ ] Enhancement
* [ ] New component

**Description:**
currency is not displaying the correct conversion. The output I get for all conversions has the same "0" output. 
<img width="253" alt="screen shot 2018-09-29 at 10 13 13 pm" src="https://user-images.githubusercontent.com/29823897/46252897-1c2fb700-c435-11e8-94ab-b273f290a407.png">
___
<img width="316" alt="screen shot 2018-09-29 at 10 13 29 pm" src="https://user-images.githubusercontent.com/29823897/46252899-25b91f00-c435-11e8-93f8-c138b0a6e9d9.png">

### If its a bug make sure to include this section.
**OS and OS version:**
* [ x] Mac
* [ ] Linux 32 Bit
* [ ] Linux 64 Bit
* [ ] Windows 32 Bit
* [ ] Windows 64 Bit

OS Version:
10.13.6

**Comment by alexanderepstein** [comment]
You are correct, something about the endpoint changed. This should be fixed in 6eb69e5ee13dc3cb516db1361b7f1f19f2f40b4c I am looking to update the version since it has been a while since I have properly done that
