### ISSUE TITLE
unable to install bash-snippets

### ISSUE THREAD

**Issue by surajgupta4** [alexanderepstein/Bash-Snippets#180]
**Issue Label:**
* [ ] Bug

**Description:**
on running  sudo add-apt-repository ppa:navanchauhan/bash-snippets
the terminal returns 
 http://ppa.launchpad.net/navanchauhan/bash-snippets/ubuntu bionic Release
  404  Not Found [IP: 10.20.1.222 3128]

The repository 'http://ppa.launchpad.net/navanchauhan/bash-snippets/ubuntu bionic Release' does not have a Release file.

### If its a bug make sure to include this section.
**OS and OS version:**

* [ ] Linux 64 Bit

OS Version:
Ubuntu 18.04

**Comment by alexanderepstein** [comment]
I would just use the git install method (it is going to be the most up to date)

**Comment by alexanderepstein** [comment]
@navanchauhan would be the one to fix the PPA

**Comment by navanchauhan** [comment]
@alexanderepstein I never got a notification about this mention somehow, I no longer have access to my Ubuntu laptop.

I am going to try and create a script for packaging this so anyone can do it in the future
