### ISSUE TITLE
More display options for weather

### ISSUE THREAD

**Issue by dashdeckers** [alexanderepstein/Bash-Snippets#182]
**Issue Label:**
* [ ] Bug
* [x] New feature
* [x] Enhancement
* [ ] New component

**Description:**
An option to only show the weather forecast for tomorrow and only displaying the current weather would be really useful for an automatic setup (this would look great on a setup worthy of the unixporn subreddit). I have tried piping the output to more/less but it doesnt display nicely at all.  
A less wide display with only 2 or 3 times of the day would also be great!

### If its a bug make sure to include this section.
**OS and OS version:**
* [ ] Mac
* [ ] Linux 32 Bit
* [ ] Linux 64 Bit
* [ ] Windows 32 Bit
* [ ] Windows 64 Bit

OS Version:

**Comment by alexanderepstein** [comment]
Not stale, just been busy I will see if I can do something like this, although it might be necessary for the wttr.in api to just support options for this

**Comment by alexanderepstein** [comment]
It actually seems that display options like that already do exist and although this was not the intent of the script it can already do this. For example if you type in ```weather Paris?0``` you will only see the current weather. Replace the 0 with a 1 to see the breakdown for the day. You can also write it like ```weather Paris?0Q``` and that will remove the line "weather report for...". All of these options can be seen [here](wttr.in/:help)
