### ISSUE TITLE
Linux tests failing "update"

### ISSUE THREAD

**Issue by virgilwashere** [alexanderepstein/Bash-Snippets#186]
**Issue Label:**
* [x] Bug
* [ ] New feature
* [ ] Enhancement
* [ ] New component

**Description:**

CI tests for Linux failing on "update" check 

### If its a bug make sure to include this section.
**OS and OS version:**
* [ ] Mac
* [ ] Linux 32 Bit
* [x] Linux 64 Bit
* [ ] Windows 32 Bit
* [ ] Windows 64 Bit

OS Version:
TravisCI

**Comment by virgilwashere** [comment]
@alexanderepstein feel free to assign this to me.


They were passing in my local Linux environment...

**Comment by alexanderepstein** [comment]
This is not the first time this has happened to me where the Linux tests work locally but do not work in Travis, I don't think I ever really pinpointed why this occurs.
