### ISSUE TITLE
Adding the sponsor button 

### ISSUE THREAD

**Issue by navanchauhan** [alexanderepstein/Bash-Snippets#189]
**Issue Label:**
* [ ] Bug
* [ ] New feature
* [x] Enhancement
* [ ] New component

**Description:**

You can enable the sponsor button by going into the project settings and enabling it

**Comment by alexanderepstein** [comment]
Closed with a54959283c29173ee61570ba9d4da71e80656ccf not really sure what this feature is yet, haven't had the time to look into it
