### ISSUE TITLE
ytview default player selection

### ISSUE THREAD

**Issue by webmastak** [alexanderepstein/Bash-Snippets#192]
Manjaro Linux 64 Bit

You can add a configuration to ytview so that you can use the default player that the user wants?

What not to do dirty hack:
My mpv player
```
getConfiguredPlayer()
{
  if [[ $(uname -s) == "Linux" ]]; then
    if command -v mpv &>/dev/null; then
      player="mpv"
    elif command -v vlc &>/dev/null; then
      player="vlc"
    elif command -v mplayer &>/dev/null; then
      player="mplayer"
    else
```

**Comment by alexanderepstein** [comment]
We can check for an environment variable to be set, if its not set we run down this list in the same order, if it is set we attempt to use that player.

**Comment by alexanderepstein** [comment]
This was just added to Version 1.23.0!
