### ISSUE TITLE
Suggestion:  create a http_get  script for all the other web utilities to use.

### ISSUE THREAD

**Issue by antofthy** [alexanderepstein/Bash-Snippets#198]
A lot of the utilities has code the look for   curl,  wget,  etc.
Add a utility to do that, and have all the other scripts use it.

Heck my own version of "http_get" can even do the request using: perl, lynx, netcat, mconnect, or gnu-awk  to make the web request, if it is needed!  It even has a pure BASH v2 method built into it.

**Comment by alexanderepstein** [comment]
I have toyed with the idea of creating a bash-snippets helpers file which would contain all the functions like these. My philosophy has been that each script file should be self contained for easier portability, but I do see the value in this. I may change my mind if someone decides to submit a pull request doing this.
