### ISSUE TITLE
[BUG] Curl not working with Weather script

### ISSUE THREAD

**Issue by whit2333** [alexanderepstein/Bash-Snippets#2]
/usr/local/bin/weather: 7: [: <html><body><a: unexpected operator
curl: option -0500&override=no%20&Comment=%0D%0A"><img: is unknown
curl: try 'curl --help' or 'curl --manual' for more information

**Comment by alexanderepstein** [comment]
What os are you on? I have tested this out on GNU Linux and OSX (which uses BSD everything) so the curl command should work

**Comment by whit2333** [comment]
Ubuntu 17.04

**Comment by alexanderepstein** [comment]
That is very interesting. I run elementary OS which is just based on the LTS version of ubuntu. Something must have happened to the curl command between these versions I will look into it and get back to you.

**Comment by alexanderepstein** [comment]
Can you try running ```wget -qO- en.wttr.in```

@chubin I think this related to the other weather curl issue

**Comment by chubin** [comment]
May be not.

@whit2333 Could you please do 

```
bash -x $(which weather) 
```

and post the output here?

**Comment by chubin** [comment]
@alexanderepstein Let us see if your new update (forced curl -A) have solved this problem

**Comment by alexanderepstein** [comment]
I haven't heard any issue here from anyone else nor a response about the status of this issue after the update, will assume it works unless I hear otherwise and will reopen this.
