### ISSUE TITLE
Improvement: add script to get command line/programing languages cheat sheets using cheat.sh

### ISSUE THREAD

**Issue by chubin** [alexanderepstein/Bash-Snippets#20]
You can use the cheat.sh service to get command line/programming languages cheat sheets.

The service delivers currently almost 1000 different cheat sheets covering 16 topics.

How can you use it?
```
    curl cheat.sh/COMMAND
```
for example:
```
    curl cheat.sh/jq
```
Or if you want to get a programming language cheat sheet, use Language/Topic:
```
    curl cheat.sh/scala/PatternMatching
    curl cheat.sh/lua/:learn
    curl cheat.sh/perl/1line
```

Use `~` for search; use `?T` to turn syntax highlighting off.

Very important: don't forget to use bash completion for this script. It's a crucial for cheat.sh, because you don't always know what is the name of the command that you are looking for.

Please check the README file of cheat.sh (https://github.com/chubin/cheat.sh) to get the whole list of its features.

Feel free to contact me if you need any help related to chetat.sh.

**Comment by alexanderepstein** [comment]
Not complete but this should cover most of the functionality f5048da5a942be341eccbae0e99f405622b8151d
