### ISSUE TITLE
Currency conversion does not work

### ISSUE THREAD

**Issue by cryptCEE** [alexanderepstein/Bash-Snippets#202]
**Issue Label: Currency conversion parse error**
* [x] Bug
* [ ] New feature
* [ ] Enhancement
* [ ] New component

**Description:**
Currency conversion does not seem to work:

```
currency EUR USD 12.35
(standard_in) 1: parse error
=========================
| EUR to USD
| Rate:
| EUR: 12.35
| USD:
=========================
```

### If its a bug make sure to include this section.
**OS and OS version:**
* [x] Mac
* [ ] Linux 32 Bit
* [ ] Linux 64 Bit
* [ ] Windows 32 Bit
* [ ] Windows 64 Bit

OS Version: Mojave 10.14.5

**Comment by alexanderepstein** [comment]
Can you try doing a manual git install of bash snippets without checking out to the latest stable release? Steps for this process are in the readme and just skip the step with the command ```git checkout```. There have been some changes to the currency script and I want to see if the error still occurs on the latest version. Doing the above process will get you the latest unreleased changes of bash-snippets.

If that does not work can you try running the command ```bash -x currency EUR USD 12.35``` and paste the output here?

**Comment by cryptCEE** [comment]
> Can you try doing a manual git install of bash snippets without checking out to the latest stable release? Steps for this process are in the readme and just skip the step with the command `git checkout`. There have been some changes to the currency script and I want to see if the error still occurs on the latest version. Doing the above process will get you the latest unreleased changes of bash-snippets.

will check it later and revert, thanks for the quick reply !

**Comment by cryptCEE** [comment]
> can you try running the command `bash -x currency EUR USD 12.35` and paste the output here?

```
bash -x currency EUR USD 12.35
+ unset base
+ unset exchangeTo
+ currentVersion=1.22.1
+ unset configuredClient
+ currencyCodes=(AUD BGN BRL CAD CHF CNY CZK DKK EUR GBP HKD HRK HUF IDR ILS INR JPY KRW MXN MYR NOK NZD PHP PLN RON RUB SEK SGD THB TRY USD ZAR)
+ getConfiguredClient
+ command -v curl
+ configuredClient=curl
+ getopts uvh opt
+ [[ 3 == 0 ]]
+ [[ 3 == \1 ]]
+ [[ 3 == \2 ]]
+ [[ 3 == \3 ]]
+ checkInternet
+ httpGet github.com
+ checkBase EUR
+ base=EUR
++ echo EUR
++ tr /a-z/ /A-Z/
+ base=EUR
++ checkValidCurrency EUR
+++ echo EUR
+++ tr -d '[:space:]'
++ [[ AUD BGN BRL CAD CHF CNY CZK DKK EUR GBP HKD HRK HUF IDR ILS INR JPY KRW MXN MYR NOK NZD PHP PLN RON RUB SEK SGD THB TRY USD ZAR == *\E\U\R* ]]
++ echo 0
+ [[ 0 == \1 ]]
+ checkExchangeTo USD
+ exchangeTo=USD
++ echo USD
++ tr /a-z/ /A-Z/
+ exchangeTo=USD
++ checkValidCurrency USD
+++ echo USD
+++ tr -d '[:space:]'
++ [[ AUD BGN BRL CAD CHF CNY CZK DKK EUR GBP HKD HRK HUF IDR ILS INR JPY KRW MXN MYR NOK NZD PHP PLN RON RUB SEK SGD THB TRY USD ZAR == *\U\S\D* ]]
++ echo 0
+ [[ 0 == \1 ]]
+ checkAmount 12.35
+ amount=12.35
+ [[ ! 12.35 =~ ^[0-9]+(\.[0-9]+)?$ ]]
+ convertCurrency
++ httpGet 'https://api.exchangeratesapi.io/latest?base=EUR'
++ case "$configuredClient" in
++ curl -A curl -s 'https://api.exchangeratesapi.io/latest?base=EUR'
++ grep -Eo 'USD":[1-9.]*'
++ grep -Eo '[0-9.]*'
+ exchangeRate=
+ command -v bc
++ echo ' * 12.35'
++ bc
(standard_in) 1: parse error
+ exchangeAmount=
+ cat
=========================
| EUR to USD
| Rate:
| EUR: 12.35
| USD:
=========================
+ exit 0
```

**Comment by cryptCEE** [comment]
> Can you try doing a manual git install of bash snippets without checking out to the latest stable release? Steps for this process are in the readme and just skip the step with the command `git checkout`. There have been some changes to the currency script and I want to see if the error still occurs on the latest version. Doing the above process will get you the latest unreleased changes of bash-snippets.

Did as advised, error still occurs:

```
currency USD EUR 12.35
(standard_in) 1: parse error
=========================
| USD to EUR
| Rate:
| USD: 12.35
| EUR:
=========================
```

**Comment by cryptCEE** [comment]
after doing manual git install as advised, bash -x currency EUR USD 12.35 gives me:

```
bash -x currency EUR USD 12.35
+ unset base
+ unset exchangeTo
+ currentVersion=1.22.1
+ unset configuredClient
+ currencyCodes=(AUD BGN BRL CAD CHF CNY CZK DKK EUR GBP HKD HRK HUF IDR ILS INR JPY KRW MXN MYR NOK NZD PHP PLN RON RUB SEK SGD THB TRY USD ZAR)
+ getConfiguredClient
+ command -v curl
+ configuredClient=curl
+ getopts uvh opt
+ [[ 3 == 0 ]]
+ [[ 3 == \1 ]]
+ [[ 3 == \2 ]]
+ [[ 3 == \3 ]]
+ checkInternet
+ httpGet github.com
+ checkBase EUR
+ base=EUR
++ echo EUR
++ tr /a-z/ /A-Z/
+ base=EUR
++ checkValidCurrency EUR
+++ echo EUR
+++ tr -d '[:space:]'
++ [[ AUD BGN BRL CAD CHF CNY CZK DKK EUR GBP HKD HRK HUF IDR ILS INR JPY KRW MXN MYR NOK NZD PHP PLN RON RUB SEK SGD THB TRY USD ZAR == *\E\U\R* ]]
++ echo 0
+ [[ 0 == \1 ]]
+ checkExchangeTo USD
+ exchangeTo=USD
++ echo USD
++ tr /a-z/ /A-Z/
+ exchangeTo=USD
++ checkValidCurrency USD
+++ echo USD
+++ tr -d '[:space:]'
++ [[ AUD BGN BRL CAD CHF CNY CZK DKK EUR GBP HKD HRK HUF IDR ILS INR JPY KRW MXN MYR NOK NZD PHP PLN RON RUB SEK SGD THB TRY USD ZAR == *\U\S\D* ]]
++ echo 0
+ [[ 0 == \1 ]]
+ checkAmount 12.35
+ amount=12.35
+ [[ ! 12.35 =~ ^[0-9]+(\.[0-9]+)?$ ]]
+ convertCurrency
++ grep -Eo 'USD":[1-9.]*'
++ httpGet 'https://api.exchangeratesapi.io/latest?base=EUR'
++ case "$configuredClient" in
++ curl -A curl -s 'https://api.exchangeratesapi.io/latest?base=EUR'
++ grep -Eo '[0-9.]*'
+ exchangeRate=
+ command -v bc
++ echo ' * 12.35'
++ bc
(standard_in) 1: parse error
+ exchangeAmount=
+ cat
=========================
| EUR to USD
| Rate:
| EUR: 12.35
| USD:
=========================
+ exit 0
```

**Comment by alexanderepstein** [comment]
It appears either that the API call is not working anymore, or they have changed the response format so we aren't parsing it correctly anymore. Will look into this
