### ISSUE TITLE
Qrify file reading bug

### ISSUE THREAD

**Issue by makeworld-the-better-one** [alexanderepstein/Bash-Snippets#203]
**Issue Label:**
* [x] Bug
* [ ] New feature
* [ ] Enhancement
* [ ] New component

**Description:**
```
~/Downloads/Bash-Snippets/cheat tags/v1.22.0
❯ qrify -d ~/Downloads/qr-code.png 
  File "<string>", line 1
    import sys, json; print json.load(sys.stdin)[0]["symbol"][0]["error"]
                               ^
SyntaxError: invalid syntax
Error:-

~/Downloads/Bash-Snippets/cheat tags/v1.22.0
❯ qrify -d '~/Downloads/qr-code.png'

~/Downloads/Bash-Snippets/cheat tags/v1.22.0
❯ qrify -d '~/Downloads/qr-code.png'

~/Downloads/Bash-Snippets/cheat tags/v1.22.0
❯ qrify -d /home/makeworld/Downloads/qr-code.png
  File "<string>", line 1
    import sys, json; print json.load(sys.stdin)[0]["symbol"][0]["error"]
                               ^
SyntaxError: invalid syntax
Error:-
```

### If its a bug make sure to include this section.
**OS and OS version:**
* [ ] Mac
* [ ] Linux 32 Bit
* [x] Linux 64 Bit
* [ ] Windows 32 Bit
* [ ] Windows 64 Bit

OS Version:
```
❯ uname -a 
Linux earth 5.2.4-arch1-1-ARCH #1 SMP PREEMPT Sun Jul 28 10:52:46 UTC 2019 x86_64 GNU/Linux
```

@alexanderepstein @linyostorovovoltos

**Comment by alexanderepstein** [comment]
When you run ```python -V``` what gets returned? Thinking this because currently python3 is not supported for all scripts. Support was just added to the stocks script for python3 so maybe we just need to implement a similar fix here.

**Comment by makeworld-the-better-one** [comment]
`Python 3.7.4` is returned, because I'm on Arch Linux. It seems the following lines should be changed from `python` to `python2` for compatibility.
```
❯ rg python
qrify
133:  error=$(echo "$JSONresponse" | python -c 'import sys, json; print json.load(sys.stdin)[0]["symbol"][0]["error"]')
137:    data=$(echo "$JSONresponse" | python -c 'import sys, json; print json.load(sys.stdin)[0]["symbol"][0]["data"]')
```

**Comment by alexanderepstein** [comment]
Okay so it looks like we will have to utilize the same logic from the stocks script to add the python3 compatibility here. Slowly, but surely all tools will soon need to support python 2 and 3. Thanks for bringing this to my attention!

**Comment by alexanderepstein** [comment]
Can you upgrade to 1.23.0 I am hoping this issue is now fixed as python3 is supported in all scripts.
