### ISSUE TITLE
stocks script not working 

### ISSUE THREAD

**Issue by rohanrdotihal** [alexanderepstein/Bash-Snippets#205]
**Issue Label:**
* [x] Bug
* [ ] New feature
* [ ] Enhancement
* [ ] New component

**Description:**
The stocks script returns Not a valid stock symbol  

### If its a bug make sure to include this section.
**OS and OS version:**
* [x] Mac
* [ ] Linux 32 Bit
* [ ] Linux 64 Bit
* [ ] Windows 32 Bit
* [ ] Windows 64 Bit

OS Version: Mojave 10.14.6

**Comment by alexanderepstein** [comment]
Can you run follow the instructions for installing bash-snippets from git? Skip the step involving a git checkout, this will give you the latest unreleased changes. I believe your issue will be fixed if you do this.

**Comment by rohanrdotihal** [comment]
Installing via git clone and skipping git checkout works fine. 
Not sure what is the issue with brew install.

**Comment by alexanderepstein** [comment]
I need to update both the git version and then update the brew version. Been a little slow to do that.
