### ISSUE TITLE
ytview not working on Mac - error message

### ISSUE THREAD

**Issue by RadeshNMP** [alexanderepstein/Bash-Snippets#206]
**Issue Label:**
* [X ] Bug
* [ ] New feature
* [ ] Enhancement
* [ ] New component

**Description:**
ytview does not work on Mac - below is the error message 
/usr/local/bin/ytview: line 91: conditional binary operator expected
/usr/local/bin/ytview: line 91: syntax error near `YTVIEWPLAYER'
/usr/local/bin/ytview: line 91: `  if [[ ! -v YTVIEWPLAYER ]]; then'

Thanks in advance,
Radesh

### If its a bug make sure to include this section.
**OS and OS version:**
* [ X] Mac
* [ ] Linux 32 Bit
* [ ] Linux 64 Bit
* [ ] Windows 32 Bit
* [ ] Windows 64 Bit

OS Version:

**Comment by alexanderepstein** [comment]
Thank you for letting me know about this! I think I have fixed it with 4c09b6ff09a193c31ba58aed37c97783a5d6e81b can you run the git install for just ytview from the instructions, however do not checkout to the latest stable release. This will give you the change I just made to ytview without me having to bump the version, If you can confirm that works now I will bump the version so everyone will be able to upgrade normally.
