### ISSUE TITLE
Multiple Tests Broken

### ISSUE THREAD

**Issue by HaoZeke** [alexanderepstein/Bash-Snippets#210]
**Issue Label:**
* [x] Bug
* [ ] New feature
* [ ] Enhancement
* [ ] New component

**Description:**
Many of the existing tests are broken at the moment. Namely:

- `cloudup`
- `crypt`
- `cryptocurrency`
- `geo`
- `meme`
- `movies`
- `newton`
- `qrify`
- `short`
- `siteciphers`
- `stocks`
- `taste`

![image](https://user-images.githubusercontent.com/4336207/69490564-f740a380-0e81-11ea-9d74-22539229e790.png)
![image](https://user-images.githubusercontent.com/4336207/69490566-fdcf1b00-0e81-11ea-9054-4288e5c89f11.png)
![image](https://user-images.githubusercontent.com/4336207/69490568-03c4fc00-0e82-11ea-8547-626c03b0ff2a.png)
![image](https://user-images.githubusercontent.com/4336207/69490569-09224680-0e82-11ea-9504-722b0c6b1429.png)
![image](https://user-images.githubusercontent.com/4336207/69490573-0fb0be00-0e82-11ea-8fdc-efe453701817.png)

These seem relatively minor and easy to fix. Will look into this later if no one else can.

### If its a bug make sure to include this section.
**OS and OS version:**
* [ ] Mac
* [ ] Linux 32 Bit
* [x] Linux 64 Bit
* [ ] Windows 32 Bit
* [ ] Windows 64 Bit

OS Version:

**Comment by alexanderepstein** [comment]
Hmm seems like way more tests are broken here than the latest travis linux build https://travis-ci.org/alexanderepstein/Bash-Snippets/jobs/616188136 so not exactly sure what is going on here. 

it would also be helpful to fix the travis darwin build, there is an issue with homebrew not having the right ruby version  (homebrew is used to install bats). Might be able to just install bats manually from github on travis darwin. 

If you were able to fix both of these things I would then be able to have passing tests for darwin and linux which is extremely useful.

However, whatever you can do is appreciated.
