### ISSUE TITLE
Pwned no longer working

### ISSUE THREAD

**Issue by navanchauhan** [alexanderepstein/Bash-Snippets#217]
**Issue Label:**
* [x] Bug
* [ ] New feature
* [ ] Enhancement
* [ ] New component

**Description:**

### If its a bug make sure to include this section.
**OS and OS version:**
* [x] Mac
* [ ] Linux 32 Bit
* [ ] Linux 64 Bit
* [ ] Windows 32 Bit
* [ ] Windows 64 Bit

OS Version:

**Comment by navanchauhan** [comment]
Have I been Pwned's API has upgraded, I'll try to make a PR soon

**Comment by navanchauhan** [comment]
The new API version, V3 requires a paid API key and the old API endpoints have been deprecated. 

@alexanderepstein please remove `pwned` from bash-snippets

**Comment by alexanderepstein** [comment]
I will remove it, thanks for the head up!
