### ISSUE TITLE
Package in the AUR

### ISSUE THREAD

**Issue by jfrcom** [alexanderepstein/Bash-Snippets#223]
**Issue Label:**
* [ ] Bug
* [x] New feature
* [ ] Enhancement
* [ ] New component

**Description:**

Hello,

I just came across this repo and saw, that the package in the AUR has been out of date since June 2018. I've built a new `PKGBUILD` and would like to take over the package. If you're fine with that you can disown the package in the AUR and make it orphan.

Just let me know about your decision.

Also thanks for the great scripts, I really like them!

**Comment by alexanderepstein** [comment]
Hey I have disowned the package, feel free to adopt it. Thanks for taking over on this!

https://aur.archlinux.org/packages/bash-snippets/

**Comment by jfrcom** [comment]
The package is now available in the AUR. Install it with
```bash
yay -S bash-snippets # replace yay with your aur helper
```

Also, I have opened a pull request where I have reworked the installing, updating, uninstalling sections and added guides for the aur package.
