### ISSUE TITLE
transfer.sh domain is not working anymore instead..

### ISSUE THREAD

**Issue by hakxcore** [alexanderepstein/Bash-Snippets#234]
**Issue Label:**
* [x] Bug
* [x] New feature
* [x] Enhancement
* [x] New component

**Description:**
transfer.sh domain is not working anymore instead can we use keep.sh in the transfer bash-snippet @alexanderepstein 

### If its a bug make sure to include this section.
**OS and OS version:**
* [x] Mac
* [x] Linux 32 Bit
* [x] Linux 64 Bit
* [x] Windows 32 Bit
* [x] Windows 64 Bit

OS Version:

**Comment by alexanderepstein** [comment]
I am happy to merge in a change that switches the tool to use keep.sh instead, but I am not sure if I have time to implement it myself

**Comment by hakxcore** [comment]
Ohk Don't worry @alexanderepstein let me create a PR.

**Comment by hakxcore** [comment]
Delayed due to the vocations :) but have created a PR toaday please consider [review](https://github.com/alexanderepstein/Bash-Snippets/pull/235l).

**Comment by alexanderepstein** [comment]
PR has been merged
