### ISSUE TITLE
movies script returns empty variable values in results

### ISSUE THREAD

**Issue by Slipjack9600** [alexanderepstein/Bash-Snippets#237]
**Issue Label:**
* [x] Bug
* [ ] New feature
* [ ] Enhancement
* [ ] New component

**Description:**
Regardless of argument (movie title) given, the script returns empty variables to the output. I checked the omdbapi URL strings and they seem legit -- i.e. I don't think omdbapi changed their formatting.

### If its a bug make sure to include this section.
**OS and OS version:**
* [ ] Mac
* [ ] Linux 32 Bit
* [x] Linux 64 Bit
* [ ] Windows 32 Bit
* [ ] Windows 64 Bit

OS Version:

**Comment by thomastubby** [comment]
Looks like the getMovieInfo() function is trying to use an invalid API key, see below:
http://www.omdbapi.com/?t=Inception&apikey=946f500a

Response | "False"
-- | --
Error | "Invalid API key!"

Upon changing a newly generated API key, the script works.

**Comment by alexanderepstein** [comment]
Should be closed with #239 thanks for the contribution 🎊
