### ISSUE TITLE
change python to python2 everywhere

### ISSUE THREAD

**Issue by jabbalaci** [alexanderepstein/Bash-Snippets#24]
Instead of calling "python -c", use "python2 -c". Under Arch / Manjaro "python" is a symbolic link pointing to python3, thus "print ..." is a syntactic error. In most distros python points to python2, thus this problem doesn't occur under Ubuntu for instance.

**Comment by alexanderepstein** [comment]
Will add this later today, thanks for the heads up

**Comment by alexanderepstein** [comment]
Fixed 44ce35f4be24ac30ab93427e74a867bf7d36d698 should be implemented in the next release

**Comment by jabbalaci** [comment]
OK. Since Python 3 is the future, think over if you want to switch to Python 3. Then print(...) is a function, i.e. the parentheses are required. And then "python3 -c ..." would be needed everywhere. But the current version with python2 is also good.
