### ISSUE TITLE
Enhancement: Youtube viewer in terminal

### ISSUE THREAD

**Issue by linyostorovovoltos** [alexanderepstein/Bash-Snippets#25]
**Issue Label:**
* [ ] bug
* [ ] feature
* [x] enhancement

**Description of bug or feature enhancement:**
So, I'm thinking that we have a script that opens up a youtube-video from the terminal. The script is already written, but there's one clincher, which is that it requires lynx. I'm trying to adapt it to use curl instead, but would this be wanted? The script is fully functional so far, and I've added uninstall and install scripts for it to my fork. 

**OS and OS version:**
* [ ] Mac
* [ ] Linux 32 Bit
* [x] Linux 64 Bit
* [ ] Windows 32 Bit
* [ ] Windows 64 Bit

OS Version: Arch Linux 64 bit

**Comment by linyostorovovoltos** [comment]
Now, I've added support for the video to play IN the terminal, but it requires caca, so I don't know if that will be wanted.

**Comment by alexanderepstein** [comment]
This definitely would be wanted if you can find a way to use curl then I can support curl wget and fetch. It is definitely more desirable if it has no dependencies for the most part all "dependencies" here should be preinstalled on most if not all distros and OSX

**Comment by linyostorovovoltos** [comment]
Alright, I'll add support for using your own video player instead of mpv.

**Comment by alexanderepstein** [comment]
Moving this conversation over to #26
