### ISSUE TITLE
A collaboration idea ( Sparrow project ) 

### ISSUE THREAD

**Issue by melezhik** [alexanderepstein/Bash-Snippets#27]
**Issue Label:**
* [ ] bug
* [ ] feature
* enhancement

**Description of bug or feature enhancement:**

Hi! I like your project. Actually I have somewhat similar project - https://sparrowhub.org , the idea is you can upload all your snippets into sparrowhub and manage them as the packages of software, don't hesitate to ask me why and how. Or we can think of other ways of bashsnippets / sparrow integration. 

Regards. 

Alexey

**OS and OS version:**
* Mac
* Linux 32 Bit
* Linux 64 Bit
* [ ] Windows 32 Bit
* [ ] Windows 64 Bit

OS Version:

**Comment by alexanderepstein** [comment]
Hey
I don't fully understand your proposal, are you asking to add these scripts to sparrowhub?

**Comment by melezhik** [comment]
hi ! Yes, I see that you have a collection of useful shell scripts. Right now the distribution is a git clone and install.sh , right ? You might upload your stuff to SparrowHub as well, the benefits you get:

- expand you community ( Sparrowhub users )
- script are easy to install on the most any Linux boxes by means of sparrow client 
- scripts are versioned, say the end user may install any version of script they want as they would do with any packages of software like Debian or Rpm packages 
- scripts have an ownership
- scripts are searchable items by either console client or by web 
- end user has an access to the scripts' documentation either by web ( markdown to HTML ) or by console
- sctipts might be run with  some binded parameters ( tasks ) defined in various formats - command line, json, yaml which easy the automation

These are some but no means are all features.

So, what do you think ? I can create an example taking one of your script and uploading it to SparrowHub to see how it works.

**Comment by alexanderepstein** [comment]
Where do things that are installed from sparrowhub get installed on the client machine? My current setup goes to ```/usr/local/bin``` is this the same? If so I wouldn't mind if you uploaded the entire repository of scripts there, the more places it is out there the better! However if the files arent installed there that will break my current update system in a confusing way that wouldn't error out at all but wouldn't update anything.

**Comment by melezhik** [comment]
The idea behind sparrow is it provides  its own mechanism of script updates, so there is no need in install.sh / update command delivered by Bash snippets repo. All  this  is pretty described  in sparrow docs - see https://github.com/melezhik/sparrow#plugins-api 

Say you have a script weather, following sparrow methodology you do this:

1. Upload script to SparrowHub with some version:

    sparrow plg upload 

2. Install script to the target machine:

    sparrow index update
    sparrow plg install weather 

3. Later on, the script developer release the new version of the script (plugin) to SparrowHub:

     sparrow plg upload 

4.  If users want to upgrade existed script (plugin) they do the same commands as above:


    sparrow index update
    sparrow plg install weather 


You can even stick with a certain version of the script (plugin) if you want:

    sparrow plg install weather --version 0.2.1

Moreover all the version of the script (plugin) are seen by SparrowHub web site.

All this is very similar to well known package distribution systems like Ruby gems, CPAN or pip. But with elemenary unit of script not library.

I have already seen your code, it seems to me that migration bash  snippets to SparrowHub won't be a big deal, as in most cases it's just a standalone bash scripts. BTW sparrow support dependencies like one can use pip, Ruby gems or CPAN Perl modules inside scripts, batteries included.

**Comment by alexanderepstein** [comment]
I am cool with adding it but i have to add a check in my updater that will throw an error if nothing has been updated and will recommend updating through the respective installed package manger. As i said for now if you installed through some other means then install.sh then calling ```tool -u``` or ```tool update``` would not return an error but actually would just update nothing and say successful. Also installing at the current moment doesn't prevent the user from doing this, so as much as I understand my update pipeline wouldn't be needed it would still exist in all of the tools and it would bring about broken functionality and even worse it doesn't aware the user it is broken. This might prove to be confusing for an end user.

**Comment by melezhik** [comment]
Sure, I don't want to break existed Bash snippets installations ))) 

I have analyzed your repository, issues and history, looks like people want to add more and more useful scripts here. I found that sparrowhub and your project shares the same goal - let people to create and share useful scripts. Imho "in scale"  it'd be hard to manage a huge number of scripts by install.sh/update as you have there. 

Say if I pick some scripts from your repo and convert them into sparrow plugins to see how one can manage and use the same scripts by means of sparrow? And if you like this examples we can think of about more deeper integration ... what do you think ?

**Comment by melezhik** [comment]
Have created https://github.com/alexanderepstein/Bash-Snippets/pull/35 as an example

**Comment by alexanderepstein** [comment]
Moving conversation over to #35
