### ISSUE TITLE
Ytviewer not working on Mac?

### ISSUE THREAD

**Issue by linyostorovovoltos** [alexanderepstein/Bash-Snippets#30]
**Issue Label:**
* [x] bug
* [ ] feature
* [ ] enhancement

**Description of bug or feature enhancement:**
So, @alexanderepstein. You say that ytviewer isn't working on mac? What is the issue? Is it not playing the video? The only problem I get when running it on a friend's mac is that there is no video player to play it with, but I'm sure if you had vlc installed it would work? Please detail the issues. 

**OS and OS version:**
* [x] Mac
* [ ] Linux 32 Bit
* [ ] Linux 64 Bit
* [ ] Windows 32 Bit
* [ ] Windows 64 Bit

OS Version:

**Comment by alexanderepstein** [comment]
I misspoke it does work on Mac now I solved the main issue in one of the commits to the fork but forgot to retest it. 
The only issue is on OSX it cannot be called as ```vlc``` it must be called as ```/Applications/VLC.app/Contents/MacOS/VLC``` which will be okay since I will automate finding the video player so the user never has to enter it.

**Comment by linyostorovovoltos** [comment]
Alright, thanks!
