### ISSUE TITLE
Add ytviewer to README.MD?

### ISSUE THREAD

**Issue by linyostorovovoltos** [alexanderepstein/Bash-Snippets#31]
**Issue Label:**
* [ ] bug
* [ ] feature
* [x] enhancement

**Description of bug or feature enhancement:** Since ytviewer is now stable, with Mac support, which hopefully is working, could it be added to the README?

**OS and OS version:**
* [x] Mac
* [x] Linux 32 Bit
* [x] Linux 64 Bit
* [ ] Windows 32 Bit
* [ ] Windows 64 Bit

OS Version:

**Comment by alexanderepstein** [comment]
The core functionality is there but it is still missing a few things. I am working on it now, will be added very shortly.

**Comment by alexanderepstein** [comment]
Added
