### ISSUE TITLE
Tabs vs Spaces for code

### ISSUE THREAD

**Issue by linyostorovovoltos** [alexanderepstein/Bash-Snippets#34]
**Issue Label:**
* [x] bug
* [ ] feature
* [ ] enhancement

**Description of bug or feature enhancement:** Should we use tabs or spaces in our code? I personally prefer tabs, but will work with anything. Just want to get a unified standard :) This isn't really urgent, so sorry for wasting your time.

**OS and OS version:**
* [ ] Mac
* [ ] Linux 32 Bit
* [X] Linux 64 Bit
* [ ] Windows 32 Bit
* [ ] Windows 64 Bit

OS Version:

**Comment by alexanderepstein** [comment]
It doesn't really matter, after I write code in bash I run it through ```beautysh``` which formats the shell scripts to a standard.

**Comment by alexanderepstein** [comment]
https://github.com/bemeurer/beautysh
