### ISSUE TITLE
Sourcing .bashrc in MacOS

### ISSUE THREAD

**Issue by mellena1** [alexanderepstein/Bash-Snippets#36]
**Issue Label:**
* [x] bug
* [ ] feature
* [ ] enhancement

**Description of bug or feature enhancement:**
MacOS defaults to sourcing ~/.bash_profile on the startup of a terminal window, so most mac users won't have a ~/.bashrc file. With the current setup it throws a `No such file or directory` error.

**OS and OS version:**
* [x] Mac
* [ ] Linux 32 Bit
* [ ] Linux 64 Bit
* [ ] Windows 32 Bit
* [ ] Windows 64 Bit

OS Version:
MacOS 10.12.5

**Comment by alexanderepstein** [comment]
Ah I even read about this but never made the connection that I sourced a non existent file. Thanks for the heads up will fix later today

**Comment by alexanderepstein** [comment]
Fixed 114a734c92931ccd8a6e22a8982c95e2ddbb839b
