### ISSUE TITLE
Calling python2 instead of python

### ISSUE THREAD

**Issue by mellena1** [alexanderepstein/Bash-Snippets#38]
**Issue Label:**
* [x] bug
* [ ] feature
* [ ] enhancement

**Description of bug or feature enhancement:**
Kind of depends on the OS and package manager the user uses, but I believe most installers install python 2.7 as `python`. This causes the scripts that utilize python to fail because the user's machine won't have anything called `python2` available in their path. There may be a way to check for what python is installed as in the path, I'm not sure though.

**OS and OS version:**
* [ ] Mac
* [ ] Linux 32 Bit
* [ ] Linux 64 Bit
* [ ] Windows 32 Bit
* [ ] Windows 64 Bit

OS Version:

**Comment by alexanderepstein** [comment]
Almost all linux distros allow to call ```python2```. I originally had it as ```python``` but for arch linux users this defaulted to python 3 which has a different print statement. I could definitely add a check at the top though to determine if i should be calling it python2 or python for that user. I haven't personally tested this on OSX too much so thanks for the heads up.

**Comment by mellena1** [comment]
Yeah no problem. Another option would be to use python3's print syntax, as it works on both python2 and python3.

**Comment by alexanderepstein** [comment]
This should fix it for now 155dd951d57297affa5e3c25077924eee3bdfb2c I just don't want to assume that a user has python3 preinstalled whereas it is almost a guarantee the user has at least python 2 already installed.
