### ISSUE TITLE
Do not use with MSys2 on Windows

### ISSUE THREAD

**Issue by okonomiyaki3000** [alexanderepstein/Bash-Snippets#4]
**Issue Label:**
* [X] bug
* [ ] feature
* [ ] enhancement

**Description of bug or feature enhancement:**

Overwrites `/usr/local/bin` instead of copying a file into it. Thanks. A lot.
Windows. MSys2.

**OS and OS version:**
* [ ] Mac
* [ ] Linux 32 Bit
* [ ] Linux 64 Bit
* [ ] Windows 32 Bit
* [X] Windows 64 Bit

OS Version:

**Comment by alexanderepstein** [comment]
Woah, I almost don't believe that, but actually on the README of this project it says that it is only for OSX and Linux, the bash is still experimental on Windows and I would never recommend this. Additionally to even enable bash you agreed to be careful and you used a sudo command without reading the script? The only reason that windows is even on the issue template is because I ported it from a different project

**Comment by okonomiyaki3000** [comment]
It did that without sudo. I don't know what's up with that.

**Comment by alexanderepstein** [comment]
Really? Is MSys2 running with elevated permissions? If I had to guess on Windows there is now situation where the user can copy files to this directory without granting permissions? I'm sorry to hear that it did this to you either way. The only logical fix i can provide is just to make it clearer not to use this on windows 7bddda933a5711f91fa160ef51759e2fc41a381c

**Comment by okonomiyaki3000** [comment]
Well, luckily I don't seem to be having any problems because of it but yeah, maybe you should just tell windows users to stay away. You can change the command to copy to `/usr/local/bin/` instead of `/usr/local/bin` but actually, after doing that, the scripts still didn't work. So I guess windows users are just SOL.

**Comment by alexanderepstein** [comment]
Do you happen to know what is stored in that folder for Windows I honestly didn't even know they had a ```/usr/local/bin/```

**Comment by okonomiyaki3000** [comment]
I think it's only an MSys2 thing. Nothing to do with Windows normally. And maybe...nothing is there unless the user specifically puts it there?

**Comment by alexanderepstein** [comment]
Possibly I would think that erasing the contents of this folder if it were to exist and be populated with what is there for UNIX and Linux systems you would definitely notice that something is wrong.
