### ISSUE TITLE
Proxy support is missing

### ISSUE THREAD

**Issue by pepik** [alexanderepstein/Bash-Snippets#46]
**Issue Label:**
* [ ] Bug
* [x] New feature
* [ ] Enhancement
* [ ] New component

**Description:**
If I am behind a proxy and don't have a direct connection to the internet, the tools fail on checkInternet function, where it runs 'nc google.com 80'. Having support for standard http_proxy and https_proxy env variables would be great. 

The python code ran after this function respects http_proxy and https_proxy settings.

This problem manifests in version provided by homebrew:
$ uname -a
Darwin somemac 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64

$ movies -v
Version 1.11.0

**Comment by alexanderepstein** [comment]
I can check for if those variables have values and skip on the checkInternet function. This will of course break the safegarud of bad output when you don't have an internet connection. Furthermore the weather application will definitely not work with no flags because your IP address will not represent your location so the geolocation will fail.

**Comment by alexanderepstein** [comment]
Can you let me know if these are set as environment variables? Does running ```env | grep "[http][s]?[_proxy]"``` return two results? If so where are these variables set, in the ```~/.bashrc``` or ```~/.bash_profile``` or neither and is this in some internet config file? Never really used a proxy consistently so I have never set it up fully. I think if i can get the correct answers to all those questions I should be able to solve the issue :smile:

**Comment by chubin** [comment]
@pepik Does weather work for you?

**Comment by MauJFernandezUVR** [comment]
I have the same issue as @pepik, neither weather, youtube view, geo -g, movies, cheat or others work.

My proxy configs are in .bashrc, both http_proxy and https_proxy are set.

**Comment by chubin** [comment]
@MauJFernandezUVR What happens if you do `curl wttr.in`?

**Comment by MauJFernandezUVR** [comment]
@chubin It works perfectly.

mauro@mauro:~$ curl wttr.in
Weather report: Buenos Aires, Argentina

     \   /     Sunny
      .-.      14-15 °C       
   ― (   ) ―   ← 22 km/h      
      `-’      10 km          
     /   \     0.2 mm

And the rest of the forecast down here.

**Comment by chubin** [comment]
Ok,  that means it is a bug in Bash-Snippets. @alexanderepstein will fix it.

**Comment by alexanderepstein** [comment]
The bug derives from the check internet function so none of the apis are the issue. Can you run test file in the attached archive? I just need to know if the two variables are blank or have values when trying to access them from a file (and one that doesn't source .bashrc)
[test.zip](https://github.com/alexanderepstein/Bash-Snippets/files/1148837/test.zip)

**Comment by chubin** [comment]
@alexanderepstein But Alex, it doesn't matter if you configured the proxy using environment variables or using some settings in the config file. It works if you start curl directly from the shell, and doesn't work if you start it using the script. That means that there is something in the script that breaks proxy support (that curl had).

**Comment by MauJFernandezUVR** [comment]
`
mauro@mauro:~/Downloads$ ./test 
./test: line 2: /home/mauro/.bash_profile: No such file or directory
http proxy variable: http://10.30.28.25:80
https proxy variable: http://10.30.28.25:80
`

And if I change the source to ~/.bashrc, I get no error:

`
mauro@mauro:~/Downloads$ ./test 
http proxy variable: http://10.30.28.25:80
https proxy variable: http://10.30.28.25:80
`

**Comment by alexanderepstein** [comment]
@chubin You are correct my solution was going to be checking for the existence of these variables $http_proxy or $https_proxy and if either of them exist I will not run my check Internet function and the rest will take care of itself. 

Thanks @MauJFernandezUVR that works it is fine that there was an error this is related to an ongoing issue #56 which will be dealt with soon but I didn't want to break existing functionality. I should be able to have all the scripts working for you by tonight or sometime tomorrow :smile:

**Comment by chubin** [comment]
@alexanderepstein You should check Internet connection in some other way that implies that curl (or some other tool) can use proxies. (May be you should simply just curl something?)

**Comment by alexanderepstein** [comment]
@chubin That makes a lot more sense as long as the method will also be compatible with ```wget``` and ```fetch```  will look into implementing a better check internet function instead of my proposed solution since I would still like to check for active internet even if the user has proxy setup.

**Comment by MauJFernandezUVR** [comment]
@alexanderepstein No problem, thanks for your work! Just ask if you need something.

**Comment by chubin** [comment]
Exactly, you could combine check of curl/fetch/wget presence on the host with the Internet connection test check. Do the first test first, and after it go to the second one (using the tool that you've found)

**Comment by alexanderepstein** [comment]
After hearing it from multiple people I think I will just remove the checkInternet function all together. Although this does prevent confusing functionality the average user does not seem to care for this as much as they dislike the amount of time it adds just to check the internet. This would also fix this issue as the rest of the tools handle proxies.

**Comment by chubin** [comment]
It is a good function, I would not remove it. It helps to debug further problem (if you have them).
Just fetch some url, say https://google.com, and if it doesn't work, the rest will not work also.
On the other hand, there could be some scripts, that don't need Internet connection at all, in this case they just switch some of them functions off

**Comment by chubin** [comment]
Another option (probably the best one):
to add some script (`snippets-api-health` or something like that), that will check Internet connectivity,
tools availability and APIs' heatlh.
```
Internet [OK]
http client [OK] (curl found)
wttr        [OK]
youtube [FAILED] Host unreachable?
fixer [OK]
```

So you'll see what does work and what does not (and why)

**Comment by alexanderepstein** [comment]
Added proxy support by using ```httpGet``` with 29ab12cd0ed03232b0f87cdd42006c1f47434c89 

@chubin It doesn't seem like a bad idea to implement a health script incase anybody has any errors I can ask them to run that and it will give me some good information, thanks for the idea

**Comment by MauJFernandezUVR** [comment]
I tested that commit and it works now!, except for cheat and qrify because the firewall has those URLs blocked.

Thanks!

**Comment by chubin** [comment]
@MauJFernandezUVR What a strange firewall. It blocks absolutely legitimate sites. Do you know the reasons?

**Comment by alexanderepstein** [comment]
Added in release <a href="https://github.com/alexanderepstein/Bash-Snippets/releases/tag/v1.11.2">1.11.2</a>

**Comment by MauJFernandezUVR** [comment]
@chubin I don't know, Websense firewall criteria, it has cheat.sh blocked as "Uncategorized". Maybe you can contact them to clarify that your web is not malicious or something like that.

**Comment by chubin** [comment]
@MauJFernandezUVR You are the only cheat.sh user (so far) who reported this problem. I hope that it is your local issue

**Comment by pepik** [comment]
Ah, I am back from my vacation and see the issue fixed. Works like a charm now, thanks!
