### ISSUE TITLE
(Termux Support) Requires ability to specify install path 

### ISSUE THREAD

**Issue by chadfurman** [alexanderepstein/Bash-Snippets#52]
**Issue Label:**
* [X] Enhancement

**Description:**
Installing in Termux fails due to assumption of /usr/local/bin and /usr/bin and /bin/bash 
while I can run the script manually with `bash install.sh`, there is zero reason to require sudo here.  Specifying a directory for all scripts to install within would be helpful, then I could that to my path manually.

**OS and OS version:**
* [x] Android 7, Termux

**Comment by alexanderepstein** [comment]
I never intended for any of these tools to be used on android. In fact a lot of them would look pretty terrible there if I had to imagine it. Additionally the install script does not require sudo but it does assume ```/usr/local/bin``` exists and attempts to copy the tool over to there. The message about sudo only occurs because some linux distros do not allow you to copy files to this directory without sudo permission (my distro Elementary OS does this). As for the issue with the assumption of ```/bin/bash``` are you referring to the <a href="https://en.wikipedia.org/wiki/Shebang_(Unix)">shebang</a> in front of all the files? If i were to remove this everybody on computers running the tools would be subjected to running the tool as ```bash tool [flags] [args]``` That seems like an unreasonable way to run a bash script. Could you imagine having to run ```bash curl [link]``` that would just be atrocious.

**Comment by alexanderepstein** [comment]
What do you think about adding an android Termux installer where it installs the files to ```/data/data/com.termux/usr/bin/```? I would put all the tools in the installer but not sure how good they would all looks since they were formatted for computer use.

**Comment by alexanderepstein** [comment]
After looking into this further it seems installing on Android would break a lot of the functionality for each of the tools. It just makes more sense to not support Android overall especially since this never was intended for that use.

**Comment by chadfurman** [comment]
@alexanderepstein qrify works fine, as do a couple other tools.  Please don't close this issue.  Let's team up on an android-compatibility layer here.  I'm planning to get a superbook, and there's a lot of projects I'll want to port to Android -- this one included.

If you re-open this issue and assign it to me, I'll aim to work on it this weekend.

**Comment by alexanderepstein** [comment]
I will reopen this for you to work on I am having trouble seeing the compatibility between my scripts and android but hopefully you can prove me wrong

**Comment by chadfurman** [comment]
In response to your comments:

`I never intended for any of these tools to be used on android. In fact a lot of them would look pretty terrible there if I had to imagine it. `

The superbook will give a nice laptop-esque terminal, and these tools will be useful.

`Additionally the install script does not require sudo but it does assume /usr/local/bin exists and attempts to copy the tool over to there. The message about sudo only occurs because some linux distros do not allow you to copy files to this directory without sudo permission (my distro Elementary OS does this).`

Understood.  But /usr/local/bin does not exist, and I don't want to root my phone just to create it.  I modified the paths in the files manually, but it's a hack and not sure it will work all the time, so I suggest configuring it.

` As for the issue with the assumption of /bin/bash are you referring to the shebang in front of all the files? If i were to remove this everybody on computers running the tools would be subjected to running the tool as bash tool [flags] [args] That seems like an unreasonable way to run a bash script. Could you imagine having to run bash curl [link] that would just be atrocious.`

Yeah that would be unacceptable.  Something in an android installer to check for /bin/bash or the path of the bash script and use sed to replace the shebang with the correct path would be useful here.

`What do you think about adding an android Termux installer where it installs the files to /data/data/com.termux/usr/bin/?`

Great idea.

` I would put all the tools in the installer but not sure how good they would all looks since they were formatted for computer use.`

Don't worry about formatting.  qrify works great with minimal adjustment (see the PR about the typo) and I imagine the other scripts will similarly fall in line with some elbow grease.

` Going to consider this as enhancement rather than a bug since this was never an intended for this use originally.`

Agreed.

`After looking into this further it seems installing on Android would break a lot of the functionality for each of the tools.`

Please elaborate.  What functionality is broken?

` It just makes more sense to not support Android overall especially since this never was intended for that use.`

I would very much like to support android.

**Comment by alexanderepstein** [comment]
The ```weather``` script will definitely look bad. Ive tried this just by running ```curl wttr.in``` on Termux. Im not sure the crypt script will work at all does Termux support ```openssl```? ```ytview``` will definitely break as it relies on vlc, mplayer or one other video player i cant remember. ```geo``` *should* break as most of the functionality relies on running checks to see whether we are dealing with linux or OSX.

**Comment by chadfurman** [comment]
Not sure about weather, as I haven't tried it yet.  If it looks bad, I bet I can add an android display layer.

Crypt works beautiful.  I installed openssl via apt.  I think I had to open a new termux session but then it just worked.

ytview would be _hilarious_ to get working (looking at you, YouTube red...) -- we'll have to just add notices for things that don't work on android.  This is 100% acceptable for now.

Why should Geo break, though?  I can do lots of networking stuff in my android CLI.  I bet we can get this working.  

```
elif [ "$(uname -s)" = "Linux" ]; then
  | ip addr show | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'
```
This is basically what we'd want to run.  I'll check my uname, but the command it probably compatible.  I have `ip` just like ubuntu.

This will be fun.

**Comment by alexanderepstein** [comment]
It seems running ```uname -s``` does return ```Linux``` so there is actually a good chance ```geo``` works flawlessly.

**Comment by alexanderepstein** [comment]
I believe #84 solves the issue with the shebang ```#!/bin/bash```

**Comment by chadfurman** [comment]
great!

**Comment by alexanderepstein** [comment]
Hey just wanted to see how this was going?

**Comment by chadfurman** [comment]
Super swamped with work.  Had to put off my OSCP studies and, with them, this project.  It's on the list :)  My superbook will be here eventually...

**Comment by chadfurman** [comment]
very excited about re-opening this ticket soon.  Such a cool project you have here!
