### ISSUE TITLE
Omdbapi is going private (used in movie)

### ISSUE THREAD

**Issue by pahakalle** [alexanderepstein/Bash-Snippets#62]
**Issue Label:**
* [X] Bug
* [ ] New feature
* [ ] Enhancement
* [ ] New component

**Description:**
So it seems Omdapi is going private in 05/08/17 (need Patreon to get api key), so that's going to make the movie script essentially not work.
Anyone happen to have any alternatives in mind?

![Omdapi frontpage announcement image](http://i.imgur.com/IV4OzQj.png)

### If its a bug make sure to include this section.
**OS and OS version:**
* [X] Mac
* [X] Linux 32 Bit
* [X] Linux 64 Bit
* [X] Windows 32 Bit
* [X] Windows 64 Bit
OS Version:

**Comment by alexanderepstein** [comment]
I am aware of this but at the moment cannot find any movie API's that will remain free and opensourced. For now movies is going to work until the api stops the key and then the script will break permanently...

**Comment by pahakalle** [comment]
Seems like https://www.themoviedb.org/ would be a good/only alternative i could find

**Comment by alexanderepstein** [comment]
They actually seem to have a decent API. When the movies script breaks hopefully I can have a replacement ready using this API.

**Comment by pahakalle** [comment]
also apparently Rotten Tomatoes also  has an api https://developer.fandango.com/Rotten_Tomatoes it needs applying tough

**Comment by pahakalle** [comment]
Of course using python to crawl a page like rotten tomatoes for info is also an option. theres a good framework  for that: https://scrapy.org/

**Comment by N3V0N** [comment]
I can configure my script according to your need https://github.com/N3V0N/TMDb

**Comment by alexanderepstein** [comment]
Using the the script by @N3V0N and modifications by me I have a backup movies script ready. For now it will sit in the movies folder under the filename [tmdb](https://github.com/alexanderepstein/Bash-Snippets/blob/master/movies/tmdb). If the movies script ever breaks I will rename it to ```movies.deprecated``` and rename ```tmdb``` to ```movies```. ```tmdb``` could be improved upon by grabbing more information. If it is able to grab more then the current movies or proves to be better in some other way but equal in information than tmdb will become the default.
