### ISSUE TITLE
Document privacy considerations

### ISSUE THREAD

**Issue by lspitzner** [alexanderepstein/Bash-Snippets#65]
What info does each script expose to which external service(s) etc?

**Comment by alexanderepstein** [comment]
This is a good idea. I am not sure exactly how to determine what information is sent to the API's during the requests. I will look into figuring this out, maybe someone else will be able to inform me how to determine this or will add this section to the README themselves

**Comment by jakewmeyer** [comment]
@alexanderepstein I can make a pass on everything and compile it to a list with information used in each script.

Probably should be a link to a separate markdown document, with a link in the readme for those actually interested, to keep the readme from getting too cluttered.

**Comment by alexanderepstein** [comment]
Will definitely do it that way thanks for helping out!
