### ISSUE TITLE
It’s unclear the poll is live; results are likely schewed

### ISSUE THREAD

**Issue by vitorgalvao** [alexanderepstein/Bash-Snippets#74]
**Issue Label:**
* [ ] Bug
* [ ] New feature
* [x] Enhancement
* [ ] New component

**Description:**

The poll in the README is neat. However, it’s not immediately apparent how it works; it’s not common for Github READMEs to be interactive. As such, I thought the poll was actually an image that was linking somewhere else (common solution in Github READMEs) and clicked anywhere to go the website of the actual poll.

I was then surprised when I saw my vote was registered, and I have no idea what I voted for.

Look closely, and you’ll see items farther down have less votes. I’m betting most people had the same reaction as me and voted for one of the top items by mistake.

### If its a bug make sure to include this section.
**OS and OS version:**
* [ ] Mac
* [ ] Linux 32 Bit
* [ ] Linux 64 Bit
* [ ] Windows 32 Bit
* [ ] Windows 64 Bit

OS Version:

**Comment by alexanderepstein** [comment]
I had a sneaking suspicion of this as I have had two polls (the second one to account for new tools) during the transition between these polls the order of the tools changed yet still the result is the most popular one is the first one in the list.

I don't really know what to do about this other than to possibly be more clear in the readme or just get rid of it all together. I just thought it would be interesting to see.

**Comment by vitorgalvao** [comment]
Two different suggestions:

+ Don’t make the full line clickable. Instead, add a “vote for this one” on each line, and only make that clickable.
+ Keep it as is, but don’t make a click count the vote immediately. Instead, redirect to a page that says “you’re voting for {{too name}}” with “yes, count my vote” and “no, I want to vote for something else” as options, and only count the vote after choosing the “yes” option.

**Comment by alexanderepstein** [comment]
The only issue is that I did not create the code that goes behind the polls only the poll itself https://github.com/tj/gh-polls so i do not have control over any of what you mentioned. My only hope would be to find another service that could let me do something similar.

**Comment by alexanderepstein** [comment]
@tj might want to see this just to see some of the issues of the polls in action

**Comment by alexanderepstein** [comment]
Just going to get rid of the poll to solve this issue as clearly the data isn't really usable anyways at this point.

**Comment by tj** [comment]
Figured programmers could deduce that it has a pointer thus you can click it haha. Not really concerned though it was just a fun Sunday project, it's more clear when it's in an issue asking for opinions

**Comment by vitorgalvao** [comment]
> Figured programmers could deduce that it has a pointer thus you can click it haha.

That’s the whole point. People do click it (which is why votes get registered) but no one is expecting a vote to be registered immediately, because that’s inconsistent with Github capabilities. If most people are failing to use properly, than it’s bad design on the poll’s part, not a failure in deduction by the user.

**Comment by tj** [comment]
Sure
