### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by damekr** [alexanderepstein/Bash-Snippets#77]
**Issue Label:**
* [x] Bug
* [ ] New feature
* [ ] Enhancement
* [ ] New component

**Description:**
Support for proxy from env variables.

### If its a bug make sure to include this section.
**OS and OS version:**
* [ ] Mac
* [ ] Linux 32 Bit
* [x] Linux 64 Bit
* [ ] Windows 32 Bit
* [ ] Windows 64 Bit

OS Version:
Arch Linux

**Comment by alexanderepstein** [comment]
Proxy support should have been added with 29ab12cd0ed03232b0f87cdd42006c1f47434c89 can you tell me what tool you are having issues with?

**Comment by damekr** [comment]
Yep, you right I was having earlier version because I made the installation from some tutorial. From master branch the newest version works!

**Comment by alexanderepstein** [comment]
Glad to hear it works for you :smile_cat:
