### ISSUE TITLE
Several improvements ideas (like that: Use LANG data when calling wttr.in)

### ISSUE THREAD

**Issue by chubin** [alexanderepstein/Bash-Snippets#8]
Hi @alexanderepstein 

Your weather script is cool, I like it, but if you make a special script instead of just curling wttr.in, I would suggest you several improvements:

1. Use your $LANG/$LC_ALL variables to access localized wttr.in version (you can specify the language using the lang= URL parameter, or using the domain name): curl de.wttr.in/Berlin
2. Check if the user has curl/httpie/wget installed, and use that one that is already installed (it will make your scripts robuster; not everyone has curl).
3. You can pass some options of your script (weather) to wttr.in. Say: wind speed, number of days for the prognose etc.

4. You can add a new feature to your script: weatherstamping of the photos (check this tweet for some inspiration: https://twitter.com/igor_chubin/status/842031115460313092

And if you need my help/new wttr.in features/improvements ideas, just contact me

**Comment by alexanderepstein** [comment]
Hey @chubin 

I definitely agree with number one I didn't even know the api had other languages, this has been added. 

For number two this is not the first time I have been told to implement this but I am still at loss because I thought every UNIX or Linux machine would have curl installed no?

I dont think I fully understand number three only because I am not sure how to do this with the api

Number 4 seems like an awesome feature and I think i am going to implement this soon.

Thanks so much for all of your suggestions, it really does help. Even further thank you for creating wttr.in it is an essential piece to this project and without it the entire weather tool would look a lot worse.

**Comment by chubin** [comment]
@alexanderepstein No, of course not. There are plenty of cases where curl is not installed at all (but there is almost always one of its alternatives: wget, fetch, etc.). Just google "curl not found" to see how often the problem occurs

Regarding options: have you tried curl wttr.in/:help ? you could implement a small wrapper, that converts your command line options into wttr.in query parameters.
Say, how do you switch between SI/USCS? With wttr.in you do it this way: curl wttr.in/Berlin?u or curl wttr.in/Amsterdam?m

So I would suggest something like:

> weather -u Berlin // weather -m Amsterdam

You could write a small wrapper that does this convertion automatically (+ a small wrapper for /:help so you could support weather --help)

**Comment by alexanderepstein** [comment]
Would it make sense to just look for curl and wget I am concerned fetch is not going to work the same as these commands and I do not have a machine to test this on at the moment.

Oh wow the api is full of options. I think I might need to rewrite my script to account for some of them, might take me a little bit but will be worth it.

**Comment by chubin** [comment]
Yes, it would make sense, but there some systems (FreeBSD is a good example) that has no curl/wget in the base system, but they have fetch instead.
with fetch you can pipe the output on the stdout, exactly as with wget:

fetch -o- wttr.in

(more on it: https://www.freebsd.org/cgi/man.cgi?fetch(1) )
So why don't support fetch?

Regarding API, I could make some helper functions for such wrapper-shell-script like yours (there are several of them already).

**Comment by alexanderepstein** [comment]
For now i am just checking if curl is installed and if not i tell the user to install it and exit but you are definitely right, I need to support fetch, hopefully I can get to doing that soon. 

As far as the helper functions go, it might be confusing unless all of the wrapper shell scripts worked the same way. Maybe I don't fully understand what the implementation of this would look like can you explain further?

**Comment by chubin** [comment]
Yes, I think it is a great idea to support not only curl but all of the clients (and even if any of them installed you can emulate them with tiny python/ruby/perl depending on that what of them is installed).
So, for example, you can do 
```
python -c 'import sys, urllib2; sys.stdout.write(urllib2.urlopen("URL").read())'
```
instead of curl URL. 

I've also noted in your code that you repeat the same call everywhere (`curl -Acurl` here, `curl -Acurl` there), I would do extract the repeating code in a separate function:

```
_curl()
{
  curl -A curl "$@"
}
```
or if you support more clients
```
_http_get()
{
  case "$_configured_http_client" in
    curl) curl -A curl "$@";;
    wget) wget -qO- "$@";;
    python) python -m "...";;
  esac
}
```
and so on. You can extend your http get client very easely in this case.

Regarding the wrapper, it is a good question. You are right, the code fully depends on the client part, but on the other hand, some of the parts can be prepared on the server side. For example some helper functions, like a converter of command line options into URL options + special URL for the modified help file (I think I should prepare some prototype and show it to you, just to be more clear).

**Comment by alexanderepstein** [comment]
I think i am going to support curl, wget and fetch for now as they seem to be the major three and the easiest to work with. I am definitely going to get rid of some of the code duplication with that, I need to also do that for all the python calls in my stocks and movies tool. 

I think I am starting to understand what you mean but still not fully if it wouldn't be too much trouble a prototype would definitely aid my comprehension.

**Comment by alexanderepstein** [comment]
I don't know if I am going to add support for the weather stamping feature unless I can find a way to get an image of the desired location and then transpose the weatherstamp onto that image but the process in its current state would not be streamlined enough for the user in my opinion.

**Comment by chubin** [comment]
I think you've understood my idea a little bit wrong.
The idea was to add weather information on the users' photos (using EXIF data of the photo files).
So you extract the GPS coordinates of the photo, fetch the weather stamp for them, 
and apply it on the photo.

Something like:
```
wttr-stamp MeAndMyGirlFriendInAlps.jpg MeAndMyGirlFriendInAlps-Weather.jpg
```
The script creates a new file, the new flle is basically the old file plus the weather stamp.

**Comment by alexanderepstein** [comment]
Ah i see, it appears location EXIF data only exists on jpgs and not all of them. Additionally I have only seen one solution that was completely bash it seems the most common practice way to do this would to be using a tool like ```imagemagick``` or something along those lines. It doesn't kill the idea behind this but makes it tougher to implement especially because from what it seems it would be impossible to do this without adding a dependency that is not native to many distros & OSX

**Comment by chubin** [comment]
Yes, you are right, but you could ask user to force location if exiftool/EXIF data is not available.
In this case it would be not a hard dependency, just a soft one, that is used if it is available.

**Comment by alexanderepstein** [comment]
That is a fair point. Will look into implementing soon.

**Comment by alexanderepstein** [comment]
Is there an option I can add to wttr.in to get the weather of a day in history and not the current weather? When adding the weather to the photos it would make sense to add the weather on that day and not the current weather. I looked through wttr.in/:help but couldn't find a function that could do this except for the moon.

**Comment by chubin** [comment]
The weather for the day is not yet supported. It will be supported in future.
