### ISSUE TITLE
Add option to backup only source repositories with Cloudup

### ISSUE THREAD

**Issue by westonganger** [alexanderepstein/Bash-Snippets#85]
**Issue Label:**
* [ ] Bug
* [ ] New feature
* [x] Enhancement
* [ ] New component

**Description:**
I went to backup my repos using `cloudup` but noticed even my old forks were being backed up. I would like to be able to only backup my source repositories using something like a `--source` option. Possibly adding a `--fork` option would also help make it more robust.

**Comment by alexanderepstein** [comment]
When I was creating the tool I didn't have any forked repositories and I had assumed the api for GitHub would only be for source repositories. Clearly this is not that case and I should support some options to handle this. Will be added soon.

**Comment by alexanderepstein** [comment]
Added with f40347cda942a88b69e85cc08b17f151bb405f9d 

Works by allowing a -s option which will only backup repositories that you did not fork

**Comment by alexanderepstein** [comment]
Released in <a href="https://github.com/alexanderepstein/Bash-Snippets/releases/tag/v1.14.0">Version 1.14.0</a>
