### ISSUE TITLE
cloudup should only create & update one bitbucket repo per github repo

### ISSUE THREAD

**Issue by westonganger** [alexanderepstein/Bash-Snippets#86]
**Issue Label:**
* [ ] Bug
* [x] New feature
* [ ] Enhancement
* [ ] New component

**Description:**
Currently `cloudup` creates repos with timestamped names. So every time you backup it creates a new repo for the new timestamp. It would be much more preferable to have it backup the repo with the same name as github (ie. Bash-Snippets --> Bash-Snippets) and continuously apply updates to the 1 bitbucket repo.

**Comment by alexanderepstein** [comment]
Added with c1b30162af477453aabc37e6c2345d8f288736ff

Works by changing the default behavior to the one stated in the issue and then making the current default behavior an option. By using ```-t``` it will append the a timestamp to the repo name always guaranteeing a unique bitbucket repository. Without the use of the ```-t``` option it will set the remote url to just the project name. This in turn will either create a new repo (if it doesn't already exist) and then push the changes.

**Comment by alexanderepstein** [comment]
Released in <a href="https://github.com/alexanderepstein/Bash-Snippets/releases/tag/v1.14.0">Version 1.14.0</a>

**Comment by alexanderepstein** [comment]
Fixed all bugs related to this with <a href="https://github.com/alexanderepstein/Bash-Snippets/releases/tag/v1.14.2">Version 1.14.2</a>
