### ISSUE TITLE
Switch encryption in crypt to gpg

### ISSUE THREAD

**Issue by linuxenko** [alexanderepstein/Bash-Snippets#91]
I've tried the enc/dec snippet and it makes me sad - it makes very weak encryption. 

Then i open the script and it contains the following:
```
openssl enc -aes-256-cbc -salt -a -in $1 -out $2 || { echo "File not found"; return 1; }
```

Lol )) Remove it or use `gpg` instead )

**Comment by alexanderepstein** [comment]
Can you explain why this encryption is weak and why gpg is better. (Just laughing about it doesn't really prove your point at all)

**Comment by linuxenko** [comment]
Decription of such method takes about 1 minute. There is such [discussions](https://stackoverflow.com/questions/16056135/how-to-use-openssl-to-encrypt-decrypt-files#comment61438116_16056298) in internet that describe with details what a problem is with weak encoding.

**Comment by alexanderepstein** [comment]
Can you link me to anything? 

> Decription of such method takes about 1 minute.

Thats not that long....

**Comment by linuxenko** [comment]
do you asking me share links to such hacking software ? hm, i dont think i will

**Comment by alexanderepstein** [comment]
I never asked for that? Not sure why you are being a why you are acting so petulant. 
I will look more into using GnuPg at some point. If you are trying to have people help you or do something for you, it would be in your best interest to act the complete opposite of how you have so far.
