### ISSUE TITLE
New

### ISSUE THREAD

**Issue by nathanbraddock** [alexanderepstein/Bash-Snippets#96]
**Issue Label:**
* [ ] Bug
* [ ] New feature
* [ ] Enhancement
* [ ] New component

**Description:**

### If its a bug make sure to include this section.
**OS and OS version:**
* [ ] Mac
* [ ] Linux 32 Bit
* [ ] Linux 64 Bit
* [ ] Windows 32 Bit
* [ ] Windows 64 Bit

OS Version:

**Comment by alexanderepstein** [comment]
Uhhh do you have an issue to report?
